/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Espace_technicien (void)
{
  GtkWidget *Espace_technicien;
  GtkWidget *fixed1aj;
  GtkWidget *affsupprimercapt;
  GtkWidget *liste;
  GtkWidget *gettrouver;
  GtkWidget *label59;
  GtkWidget *affsupperror;
  GtkWidget *afficheraj;
  GtkWidget *alignment7aj;
  GtkWidget *hbox7aj;
  GtkWidget *image14aj;
  GtkWidget *label26;
  GtkWidget *label25;
  GtkWidget *label6;
  GtkWidget *label5;
  GtkWidget *conf_suppr;
  GtkWidget *buttonsortie;
  GtkWidget *alignment10aj;
  GtkWidget *hbox10aj;
  GtkWidget *image17aj;
  GtkWidget *label62aj;
  GtkWidget *label60;
  GtkWidget *afftrouverror;
  GtkWidget *afftouver;
  GtkWidget *alignment4aj;
  GtkWidget *hbox4aj;
  GtkWidget *image4aj;
  GtkWidget *label22;
  GtkWidget *gotomodifiercapteur;
  GtkWidget *alignment3aj;
  GtkWidget *hbox3aj;
  GtkWidget *image21aj;
  GtkWidget *label21;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *affsupprimer;
  GtkWidget *alignment2aj;
  GtkWidget *hbox2aj;
  GtkWidget *image2aj;
  GtkWidget *label20;
  GtkWidget *on_gotoajoutercapt;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image23aj;
  GtkWidget *label67;
  GtkWidget *gotoalarme;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image1;
  GtkWidget *label68;
  GtkWidget *label27;
  GtkWidget *label61;

  Espace_technicien = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_technicien), _("Espace technicien"));

  fixed1aj = gtk_fixed_new ();
  gtk_widget_show (fixed1aj);
  gtk_container_add (GTK_CONTAINER (Espace_technicien), fixed1aj);

  affsupprimercapt = gtk_entry_new ();
  gtk_widget_show (affsupprimercapt);
  gtk_fixed_put (GTK_FIXED (fixed1aj), affsupprimercapt, 656, 232);
  gtk_widget_set_size_request (affsupprimercapt, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (affsupprimercapt), 8226);

  liste = gtk_tree_view_new ();
  gtk_widget_show (liste);
  gtk_fixed_put (GTK_FIXED (fixed1aj), liste, 152, 168);
  gtk_widget_set_size_request (liste, 408, 408);

  gettrouver = gtk_entry_new ();
  gtk_widget_show (gettrouver);
  gtk_fixed_put (GTK_FIXED (fixed1aj), gettrouver, 648, 456);
  gtk_widget_set_size_request (gettrouver, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (gettrouver), 8226);

  label59 = gtk_label_new ("");
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label59, 616, 336);
  gtk_widget_set_size_request (label59, 224, 16);

  affsupperror = gtk_label_new ("");
  gtk_widget_show (affsupperror);
  gtk_fixed_put (GTK_FIXED (fixed1aj), affsupperror, 632, 280);
  gtk_widget_set_size_request (affsupperror, 184, 16);

  afficheraj = gtk_button_new ();
  gtk_widget_show (afficheraj);
  gtk_fixed_put (GTK_FIXED (fixed1aj), afficheraj, 592, 560);
  gtk_widget_set_size_request (afficheraj, 120, 32);

  alignment7aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7aj);
  gtk_container_add (GTK_CONTAINER (afficheraj), alignment7aj);

  hbox7aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7aj);
  gtk_container_add (GTK_CONTAINER (alignment7aj), hbox7aj);

  image14aj = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14aj);
  gtk_box_pack_start (GTK_BOX (hbox7aj), image14aj, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox7aj), label26, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("Actualiser"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label25, 568, 544);
  gtk_widget_set_size_request (label25, 160, 16);

  label6 = gtk_label_new (_("Trouver un capteur"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label6, 648, 432);
  gtk_widget_set_size_request (label6, 152, 16);

  label5 = gtk_label_new (_("Modifier les donn\303\251es d'un capteur"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label5, 600, 360);
  gtk_widget_set_size_request (label5, 264, 16);

  conf_suppr = gtk_check_button_new_with_mnemonic (_("Etes-vous sure de supprimer le capteur"));
  gtk_widget_show (conf_suppr);
  gtk_fixed_put (GTK_FIXED (fixed1aj), conf_suppr, 592, 256);
  gtk_widget_set_size_request (conf_suppr, 296, 24);

  buttonsortie = gtk_button_new ();
  gtk_widget_show (buttonsortie);
  gtk_fixed_put (GTK_FIXED (fixed1aj), buttonsortie, 16, 568);
  gtk_widget_set_size_request (buttonsortie, 104, 32);

  alignment10aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10aj);
  gtk_container_add (GTK_CONTAINER (buttonsortie), alignment10aj);

  hbox10aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10aj);
  gtk_container_add (GTK_CONTAINER (alignment10aj), hbox10aj);

  image17aj = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17aj);
  gtk_box_pack_start (GTK_BOX (hbox10aj), image17aj, FALSE, FALSE, 0);

  label62aj = gtk_label_new_with_mnemonic (_("Sortie"));
  gtk_widget_show (label62aj);
  gtk_box_pack_start (GTK_BOX (hbox10aj), label62aj, FALSE, FALSE, 0);

  label60 = gtk_label_new (_("Bienvenue dans la gestion des capteurs"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label60, 288, 24);
  gtk_widget_set_size_request (label60, 344, 56);

  afftrouverror = gtk_label_new ("");
  gtk_widget_show (afftrouverror);
  gtk_fixed_put (GTK_FIXED (fixed1aj), afftrouverror, 664, 520);
  gtk_widget_set_size_request (afftrouverror, 136, 17);

  afftouver = gtk_button_new ();
  gtk_widget_show (afftouver);
  gtk_fixed_put (GTK_FIXED (fixed1aj), afftouver, 688, 488);
  gtk_widget_set_size_request (afftouver, 88, 32);

  alignment4aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4aj);
  gtk_container_add (GTK_CONTAINER (afftouver), alignment4aj);

  hbox4aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4aj);
  gtk_container_add (GTK_CONTAINER (alignment4aj), hbox4aj);

  image4aj = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4aj);
  gtk_box_pack_start (GTK_BOX (hbox4aj), image4aj, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Trouver"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox4aj), label22, FALSE, FALSE, 0);

  gotomodifiercapteur = gtk_button_new ();
  gtk_widget_show (gotomodifiercapteur);
  gtk_fixed_put (GTK_FIXED (fixed1aj), gotomodifiercapteur, 680, 376);
  gtk_widget_set_size_request (gotomodifiercapteur, 96, 32);

  alignment3aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3aj);
  gtk_container_add (GTK_CONTAINER (gotomodifiercapteur), alignment3aj);

  hbox3aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3aj);
  gtk_container_add (GTK_CONTAINER (alignment3aj), hbox3aj);

  image21aj = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21aj);
  gtk_box_pack_start (GTK_BOX (hbox3aj), image21aj, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox3aj), label21, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Ajouter capteur"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label1, 648, 144);
  gtk_widget_set_size_request (label1, 160, 32);

  label2 = gtk_label_new (_("Supprimer un capteur"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label2, 664, 216);
  gtk_widget_set_size_request (label2, 152, 16);

  affsupprimer = gtk_button_new ();
  gtk_widget_show (affsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed1aj), affsupprimer, 680, 296);
  gtk_widget_set_size_request (affsupprimer, 104, 32);

  alignment2aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2aj);
  gtk_container_add (GTK_CONTAINER (affsupprimer), alignment2aj);

  hbox2aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2aj);
  gtk_container_add (GTK_CONTAINER (alignment2aj), hbox2aj);

  image2aj = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2aj);
  gtk_box_pack_start (GTK_BOX (hbox2aj), image2aj, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox2aj), label20, FALSE, FALSE, 0);

  on_gotoajoutercapt = gtk_button_new ();
  gtk_widget_show (on_gotoajoutercapt);
  gtk_fixed_put (GTK_FIXED (fixed1aj), on_gotoajoutercapt, 688, 176);
  gtk_widget_set_size_request (on_gotoajoutercapt, 88, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (on_gotoajoutercapt), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image23aj = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23aj);
  gtk_box_pack_start (GTK_BOX (hbox15), image23aj, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox15), label67, FALSE, FALSE, 0);

  gotoalarme = gtk_button_new ();
  gtk_widget_show (gotoalarme);
  gtk_fixed_put (GTK_FIXED (fixed1aj), gotoalarme, 744, 560);
  gtk_widget_set_size_request (gotoalarme, 136, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (gotoalarme), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image1 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox16), image1, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_(" D\303\251bit d'eau"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox16), label68, FALSE, FALSE, 0);

  label27 = gtk_label_new (_("Afficher d\303\251bit d'eau"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label27, 736, 544);
  gtk_widget_set_size_request (label27, 144, 16);

  label61 = gtk_label_new (_("Les capteurs utilis\303\251s sont :"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed1aj), label61, 128, 144);
  gtk_widget_set_size_request (label61, 224, 16);

  g_signal_connect ((gpointer) liste, "row_activated",
                    G_CALLBACK (on_liste_row_activated),
                    NULL);
  g_signal_connect ((gpointer) afficheraj, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) conf_suppr, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonsortie, "clicked",
                    G_CALLBACK (on_buttonsortie_clicked),
                    NULL);
  g_signal_connect ((gpointer) afftouver, "clicked",
                    G_CALLBACK (on_afftouver_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotomodifiercapteur, "clicked",
                    G_CALLBACK (on_gotomodifiercapteur_clicked),
                    NULL);
  g_signal_connect ((gpointer) affsupprimer, "clicked",
                    G_CALLBACK (on_affsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) on_gotoajoutercapt, "clicked",
                    G_CALLBACK (on_gotoajoutercapt_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotoalarme, "clicked",
                    G_CALLBACK (on_gotoalarme_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_technicien, Espace_technicien, "Espace_technicien");
  GLADE_HOOKUP_OBJECT (Espace_technicien, fixed1aj, "fixed1aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, affsupprimercapt, "affsupprimercapt");
  GLADE_HOOKUP_OBJECT (Espace_technicien, liste, "liste");
  GLADE_HOOKUP_OBJECT (Espace_technicien, gettrouver, "gettrouver");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label59, "label59");
  GLADE_HOOKUP_OBJECT (Espace_technicien, affsupperror, "affsupperror");
  GLADE_HOOKUP_OBJECT (Espace_technicien, afficheraj, "afficheraj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment7aj, "alignment7aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox7aj, "hbox7aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image14aj, "image14aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label26, "label26");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label25, "label25");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label6, "label6");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label5, "label5");
  GLADE_HOOKUP_OBJECT (Espace_technicien, conf_suppr, "conf_suppr");
  GLADE_HOOKUP_OBJECT (Espace_technicien, buttonsortie, "buttonsortie");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment10aj, "alignment10aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox10aj, "hbox10aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image17aj, "image17aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label62aj, "label62aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label60, "label60");
  GLADE_HOOKUP_OBJECT (Espace_technicien, afftrouverror, "afftrouverror");
  GLADE_HOOKUP_OBJECT (Espace_technicien, afftouver, "afftouver");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment4aj, "alignment4aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox4aj, "hbox4aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image4aj, "image4aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label22, "label22");
  GLADE_HOOKUP_OBJECT (Espace_technicien, gotomodifiercapteur, "gotomodifiercapteur");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment3aj, "alignment3aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox3aj, "hbox3aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image21aj, "image21aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label21, "label21");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label1, "label1");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label2, "label2");
  GLADE_HOOKUP_OBJECT (Espace_technicien, affsupprimer, "affsupprimer");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment2aj, "alignment2aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox2aj, "hbox2aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image2aj, "image2aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label20, "label20");
  GLADE_HOOKUP_OBJECT (Espace_technicien, on_gotoajoutercapt, "on_gotoajoutercapt");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image23aj, "image23aj");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label67, "label67");
  GLADE_HOOKUP_OBJECT (Espace_technicien, gotoalarme, "gotoalarme");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image1, "image1");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label68, "label68");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label27, "label27");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label61, "label61");

  return Espace_technicien;
}

GtkWidget*
create_Ajouter_un_capteur (void)
{
  GtkWidget *Ajouter_un_capteur;
  GtkWidget *fixed2aj;
  GtkWidget *ajouterid;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *ajouterposition;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *ajoutertype;
  GtkWidget *buttonacc1;
  GtkWidget *alignment11aj;
  GtkWidget *hbox11aj;
  GtkWidget *image18aj;
  GtkWidget *label63aj;
  GtkWidget *label31;
  GtkWidget *ajoutervalider;
  GtkWidget *alignment5aj;
  GtkWidget *hbox5aj;
  GtkWidget *image7aj;
  GtkWidget *label23;
  GtkWidget *ajoutererror;

  Ajouter_un_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_un_capteur), _("Ajouter un capteur"));

  fixed2aj = gtk_fixed_new ();
  gtk_widget_show (fixed2aj);
  gtk_container_add (GTK_CONTAINER (Ajouter_un_capteur), fixed2aj);

  ajouterid = gtk_entry_new ();
  gtk_widget_show (ajouterid);
  gtk_fixed_put (GTK_FIXED (fixed2aj), ajouterid, 288, 272);
  gtk_widget_set_size_request (ajouterid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajouterid), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2aj), spinbutton1, 288, 432);
  gtk_widget_set_size_request (spinbutton1, 160, 32);

  ajouterposition = gtk_entry_new ();
  gtk_widget_show (ajouterposition);
  gtk_fixed_put (GTK_FIXED (fixed2aj), ajouterposition, 288, 376);
  gtk_widget_set_size_request (ajouterposition, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ajouterposition), 8226);

  label8 = gtk_label_new (_("Ajouter un nouveau capteur"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2aj), label8, 248, 200);
  gtk_widget_set_size_request (label8, 232, 16);

  label9 = gtk_label_new (_("ID:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2aj), label9, 248, 280);
  gtk_widget_set_size_request (label9, 40, 16);

  label10 = gtk_label_new (_("Type:"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2aj), label10, 240, 328);
  gtk_widget_set_size_request (label10, 49, 17);

  label11 = gtk_label_new (_("Position:"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2aj), label11, 224, 384);
  gtk_widget_set_size_request (label11, 64, 16);

  ajoutertype = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ajoutertype);
  gtk_fixed_put (GTK_FIXED (fixed2aj), ajoutertype, 288, 320);
  gtk_widget_set_size_request (ajoutertype, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajoutertype), _("Flame"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajoutertype), _("Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajoutertype), _("Mouvement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajoutertype), _("Gaz"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ajoutertype), _("Sonore"));

  buttonacc1 = gtk_button_new ();
  gtk_widget_show (buttonacc1);
  gtk_fixed_put (GTK_FIXED (fixed2aj), buttonacc1, 80, 512);
  gtk_widget_set_size_request (buttonacc1, 96, 32);

  alignment11aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11aj);
  gtk_container_add (GTK_CONTAINER (buttonacc1), alignment11aj);

  hbox11aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11aj);
  gtk_container_add (GTK_CONTAINER (alignment11aj), hbox11aj);

  image18aj = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18aj);
  gtk_box_pack_start (GTK_BOX (hbox11aj), image18aj, FALSE, FALSE, 0);

  label63aj = gtk_label_new_with_mnemonic (_("Accueil"));
  gtk_widget_show (label63aj);
  gtk_box_pack_start (GTK_BOX (hbox11aj), label63aj, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("Valeur:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed2aj), label31, 224, 440);
  gtk_widget_set_size_request (label31, 57, 16);

  ajoutervalider = gtk_button_new ();
  gtk_widget_show (ajoutervalider);
  gtk_fixed_put (GTK_FIXED (fixed2aj), ajoutervalider, 328, 480);
  gtk_widget_set_size_request (ajoutervalider, 80, 32);

  alignment5aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5aj);
  gtk_container_add (GTK_CONTAINER (ajoutervalider), alignment5aj);

  hbox5aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5aj);
  gtk_container_add (GTK_CONTAINER (alignment5aj), hbox5aj);

  image7aj = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7aj);
  gtk_box_pack_start (GTK_BOX (hbox5aj), image7aj, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox5aj), label23, FALSE, FALSE, 0);

  ajoutererror = gtk_label_new ("");
  gtk_widget_show (ajoutererror);
  gtk_fixed_put (GTK_FIXED (fixed2aj), ajoutererror, 216, 512);
  gtk_widget_set_size_request (ajoutererror, 304, 32);

  g_signal_connect ((gpointer) buttonacc1, "clicked",
                    G_CALLBACK (on_buttonacc1_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajoutervalider, "clicked",
                    G_CALLBACK (on_ajoutervalider_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_un_capteur, Ajouter_un_capteur, "Ajouter_un_capteur");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, fixed2aj, "fixed2aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, ajouterid, "ajouterid");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, ajouterposition, "ajouterposition");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, label8, "label8");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, label9, "label9");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, label10, "label10");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, label11, "label11");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, ajoutertype, "ajoutertype");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, buttonacc1, "buttonacc1");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, alignment11aj, "alignment11aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, hbox11aj, "hbox11aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, image18aj, "image18aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, label63aj, "label63aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, label31, "label31");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, ajoutervalider, "ajoutervalider");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, alignment5aj, "alignment5aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, hbox5aj, "hbox5aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, image7aj, "image7aj");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, label23, "label23");
  GLADE_HOOKUP_OBJECT (Ajouter_un_capteur, ajoutererror, "ajoutererror");

  return Ajouter_un_capteur;
}

GtkWidget*
create_modifier_un_capteur (void)
{
  GtkWidget *modifier_un_capteur;
  GtkWidget *fixed3aj;
  GtkWidget *modifid;
  GtkObject *spinbutton2aj_adj;
  GtkWidget *spinbutton2aj;
  GtkWidget *modifposition;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *modifvalider;
  GtkWidget *alignment6aj;
  GtkWidget *hbox6aj;
  GtkWidget *image10aj;
  GtkWidget *label24;
  GtkWidget *label16;
  GtkWidget *buttonacc2;
  GtkWidget *alignment12aj;
  GtkWidget *hbox12aj;
  GtkWidget *image19aj;
  GtkWidget *label64aj;
  GtkWidget *label17;
  GtkWidget *modiftype;
  GtkWidget *label18;
  GtkWidget *modifetat;
  GtkWidget *affmodifiererror;
  GtkWidget *label32;

  modifier_un_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_un_capteur), _("modifier un capteur"));

  fixed3aj = gtk_fixed_new ();
  gtk_widget_show (fixed3aj);
  gtk_container_add (GTK_CONTAINER (modifier_un_capteur), fixed3aj);

  modifid = gtk_entry_new ();
  gtk_widget_show (modifid);
  gtk_fixed_put (GTK_FIXED (fixed3aj), modifid, 240, 240);
  gtk_widget_set_size_request (modifid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifid), 8226);

  spinbutton2aj_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2aj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2aj_adj), 1, 0);
  gtk_widget_show (spinbutton2aj);
  gtk_fixed_put (GTK_FIXED (fixed3aj), spinbutton2aj, 240, 432);
  gtk_widget_set_size_request (spinbutton2aj, 160, 24);

  modifposition = gtk_entry_new ();
  gtk_widget_show (modifposition);
  gtk_fixed_put (GTK_FIXED (fixed3aj), modifposition, 240, 336);
  gtk_widget_set_size_request (modifposition, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modifposition), 8226);

  label14 = gtk_label_new (_("Modifier un capteur\n\t(Existant!)"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3aj), label14, 216, 128);
  gtk_widget_set_size_request (label14, 216, 88);

  label15 = gtk_label_new (_("Donner ID:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3aj), label15, 152, 240);
  gtk_widget_set_size_request (label15, 88, 24);

  modifvalider = gtk_button_new ();
  gtk_widget_show (modifvalider);
  gtk_fixed_put (GTK_FIXED (fixed3aj), modifvalider, 272, 488);
  gtk_widget_set_size_request (modifvalider, 96, 32);

  alignment6aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6aj);
  gtk_container_add (GTK_CONTAINER (modifvalider), alignment6aj);

  hbox6aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6aj);
  gtk_container_add (GTK_CONTAINER (alignment6aj), hbox6aj);

  image10aj = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10aj);
  gtk_box_pack_start (GTK_BOX (hbox6aj), image10aj, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox6aj), label24, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("Type:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3aj), label16, 184, 296);
  gtk_widget_set_size_request (label16, 49, 17);

  buttonacc2 = gtk_button_new ();
  gtk_widget_show (buttonacc2);
  gtk_fixed_put (GTK_FIXED (fixed3aj), buttonacc2, 32, 520);
  gtk_widget_set_size_request (buttonacc2, 88, 32);

  alignment12aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12aj);
  gtk_container_add (GTK_CONTAINER (buttonacc2), alignment12aj);

  hbox12aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12aj);
  gtk_container_add (GTK_CONTAINER (alignment12aj), hbox12aj);

  image19aj = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19aj);
  gtk_box_pack_start (GTK_BOX (hbox12aj), image19aj, FALSE, FALSE, 0);

  label64aj = gtk_label_new_with_mnemonic (_("Accueil"));
  gtk_widget_show (label64aj);
  gtk_box_pack_start (GTK_BOX (hbox12aj), label64aj, FALSE, FALSE, 0);

  label17 = gtk_label_new (_("Position:"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3aj), label17, 160, 336);
  gtk_widget_set_size_request (label17, 80, 32);

  modiftype = gtk_combo_box_entry_new_text ();
  gtk_widget_show (modiftype);
  gtk_fixed_put (GTK_FIXED (fixed3aj), modiftype, 240, 288);
  gtk_widget_set_size_request (modiftype, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (modiftype), _("Flame"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modiftype), _("Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modiftype), _("Mouvement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modiftype), _("Gaz"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modiftype), _("Sonore"));

  label18 = gtk_label_new (_("Etat en %:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3aj), label18, 160, 393);
  gtk_widget_set_size_request (label18, 73, 16);

  modifetat = gtk_combo_box_entry_new_text ();
  gtk_widget_show (modifetat);
  gtk_fixed_put (GTK_FIXED (fixed3aj), modifetat, 240, 384);
  gtk_widget_set_size_request (modifetat, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (modifetat), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modifetat), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modifetat), _("50"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modifetat), _("75"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (modifetat), _("100"));

  affmodifiererror = gtk_label_new ("");
  gtk_widget_show (affmodifiererror);
  gtk_fixed_put (GTK_FIXED (fixed3aj), affmodifiererror, 168, 456);
  gtk_widget_set_size_request (affmodifiererror, 312, 24);

  label32 = gtk_label_new (_("Valeur:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed3aj), label32, 168, 432);
  gtk_widget_set_size_request (label32, 72, 16);

  g_signal_connect ((gpointer) modifvalider, "clicked",
                    G_CALLBACK (on_modifvalider_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonacc2, "clicked",
                    G_CALLBACK (on_buttonacc2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_un_capteur, modifier_un_capteur, "modifier_un_capteur");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, fixed3aj, "fixed3aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, modifid, "modifid");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, spinbutton2aj, "spinbutton2aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, modifposition, "modifposition");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, modifvalider, "modifvalider");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, alignment6aj, "alignment6aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, hbox6aj, "hbox6aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, image10aj, "image10aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, buttonacc2, "buttonacc2");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, alignment12aj, "alignment12aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, hbox12aj, "hbox12aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, image19aj, "image19aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label64aj, "label64aj");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, modiftype, "modiftype");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, modifetat, "modifetat");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, affmodifiererror, "affmodifiererror");
  GLADE_HOOKUP_OBJECT (modifier_un_capteur, label32, "label32");

  return modifier_un_capteur;
}

GtkWidget*
create_afficher_debit (void)
{
  GtkWidget *afficher_debit;
  GtkWidget *fixed4aj;
  GtkWidget *fixed6aj;
  GtkWidget *buttonacc3;
  GtkWidget *alignment13aj;
  GtkWidget *hbox13aj;
  GtkWidget *image20aj;
  GtkWidget *label65aj;
  GtkWidget *scrolledwindow1aj;
  GtkWidget *textview1aj;
  GtkWidget *label29;
  GtkWidget *affichercapteur;
  GtkWidget *alignment9aj;
  GtkWidget *hbox9aj;
  GtkWidget *image16aj;
  GtkWidget *label30;

  afficher_debit = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher_debit), _("afficher alarme"));

  fixed4aj = gtk_fixed_new ();
  gtk_widget_show (fixed4aj);
  gtk_container_add (GTK_CONTAINER (afficher_debit), fixed4aj);

  fixed6aj = gtk_fixed_new ();
  gtk_widget_show (fixed6aj);
  gtk_fixed_put (GTK_FIXED (fixed4aj), fixed6aj, 472, 464);
  gtk_widget_set_size_request (fixed6aj, 50, 50);

  buttonacc3 = gtk_button_new ();
  gtk_widget_show (buttonacc3);
  gtk_fixed_put (GTK_FIXED (fixed4aj), buttonacc3, 16, 464);
  gtk_widget_set_size_request (buttonacc3, 88, 32);

  alignment13aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13aj);
  gtk_container_add (GTK_CONTAINER (buttonacc3), alignment13aj);

  hbox13aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13aj);
  gtk_container_add (GTK_CONTAINER (alignment13aj), hbox13aj);

  image20aj = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20aj);
  gtk_box_pack_start (GTK_BOX (hbox13aj), image20aj, FALSE, FALSE, 0);

  label65aj = gtk_label_new_with_mnemonic (_("Accueil"));
  gtk_widget_show (label65aj);
  gtk_box_pack_start (GTK_BOX (hbox13aj), label65aj, FALSE, FALSE, 0);

  scrolledwindow1aj = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1aj);
  gtk_fixed_put (GTK_FIXED (fixed4aj), scrolledwindow1aj, 120, 144);
  gtk_widget_set_size_request (scrolledwindow1aj, 504, 264);

  textview1aj = gtk_text_view_new ();
  gtk_widget_show (textview1aj);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1aj), textview1aj);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview1aj), FALSE);
  gtk_text_view_set_overwrite (GTK_TEXT_VIEW (textview1aj), TRUE);

  label29 = gtk_label_new (_("Le debit d'eau"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4aj), label29, 280, 96);
  gtk_widget_set_size_request (label29, 160, 56);

  affichercapteur = gtk_button_new ();
  gtk_widget_show (affichercapteur);
  gtk_fixed_put (GTK_FIXED (fixed4aj), affichercapteur, 320, 432);
  gtk_widget_set_size_request (affichercapteur, 90, 40);

  alignment9aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9aj);
  gtk_container_add (GTK_CONTAINER (affichercapteur), alignment9aj);

  hbox9aj = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9aj);
  gtk_container_add (GTK_CONTAINER (alignment9aj), hbox9aj);

  image16aj = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16aj);
  gtk_box_pack_start (GTK_BOX (hbox9aj), image16aj, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox9aj), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonacc3, "clicked",
                    G_CALLBACK (on_buttonacc3_clicked),
                    NULL);
  g_signal_connect ((gpointer) affichercapteur, "clicked",
                    G_CALLBACK (on_affichercapteur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher_debit, afficher_debit, "afficher_debit");
  GLADE_HOOKUP_OBJECT (afficher_debit, fixed4aj, "fixed4aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, fixed6aj, "fixed6aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, buttonacc3, "buttonacc3");
  GLADE_HOOKUP_OBJECT (afficher_debit, alignment13aj, "alignment13aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, hbox13aj, "hbox13aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, image20aj, "image20aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, label65aj, "label65aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, scrolledwindow1aj, "scrolledwindow1aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, textview1aj, "textview1aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, label29, "label29");
  GLADE_HOOKUP_OBJECT (afficher_debit, affichercapteur, "affichercapteur");
  GLADE_HOOKUP_OBJECT (afficher_debit, alignment9aj, "alignment9aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, hbox9aj, "hbox9aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, image16aj, "image16aj");
  GLADE_HOOKUP_OBJECT (afficher_debit, label30, "label30");

  return afficher_debit;
}

GtkWidget*
create_confirmation (void)
{
  GtkWidget *confirmation;
  GtkWidget *fixed5aj;
  GtkWidget *label33;
  GtkWidget *radiobutton2aj;
  GSList *radiobutton2aj_group = NULL;
  GtkWidget *radiobutton1aj;
  GtkWidget *button1aj;
  GtkWidget *alignment14aj;
  GtkWidget *hbox14;
  GtkWidget *image22aj;
  GtkWidget *label66;

  confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (confirmation), _("confirmation"));

  fixed5aj = gtk_fixed_new ();
  gtk_widget_show (fixed5aj);
  gtk_container_add (GTK_CONTAINER (confirmation), fixed5aj);

  label33 = gtk_label_new (_("Voulez-vous quitt\303\251 ?"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5aj), label33, 104, 24);
  gtk_widget_set_size_request (label33, 184, 24);

  radiobutton2aj = gtk_radio_button_new_with_mnemonic (NULL, _("Non"));
  gtk_widget_show (radiobutton2aj);
  gtk_fixed_put (GTK_FIXED (fixed5aj), radiobutton2aj, 232, 72);
  gtk_widget_set_size_request (radiobutton2aj, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2aj), radiobutton2aj_group);
  radiobutton2aj_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2aj));

  radiobutton1aj = gtk_radio_button_new_with_mnemonic (NULL, _("Oui"));
  gtk_widget_show (radiobutton1aj);
  gtk_fixed_put (GTK_FIXED (fixed5aj), radiobutton1aj, 96, 72);
  gtk_widget_set_size_request (radiobutton1aj, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1aj), radiobutton2aj_group);
  radiobutton2aj_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1aj));

  button1aj = gtk_button_new ();
  gtk_widget_show (button1aj);
  gtk_fixed_put (GTK_FIXED (fixed5aj), button1aj, 152, 128);
  gtk_widget_set_size_request (button1aj, 88, 40);

  alignment14aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14aj);
  gtk_container_add (GTK_CONTAINER (button1aj), alignment14aj);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14aj), hbox14);

  image22aj = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22aj);
  gtk_box_pack_start (GTK_BOX (hbox14), image22aj, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox14), label66, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton2aj, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1aj, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) button1aj, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmation, confirmation, "confirmation");
  GLADE_HOOKUP_OBJECT (confirmation, fixed5aj, "fixed5aj");
  GLADE_HOOKUP_OBJECT (confirmation, label33, "label33");
  GLADE_HOOKUP_OBJECT (confirmation, radiobutton2aj, "radiobutton2aj");
  GLADE_HOOKUP_OBJECT (confirmation, radiobutton1aj, "radiobutton1aj");
  GLADE_HOOKUP_OBJECT (confirmation, button1aj, "button1aj");
  GLADE_HOOKUP_OBJECT (confirmation, alignment14aj, "alignment14aj");
  GLADE_HOOKUP_OBJECT (confirmation, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (confirmation, image22aj, "image22aj");
  GLADE_HOOKUP_OBJECT (confirmation, label66, "label66");

  return confirmation;
}

