/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Espace_technicien (void);
GtkWidget* create_Ajouter_un_capteur (void);
GtkWidget* create_modifier_un_capteur (void);
GtkWidget* create_afficher_debit (void);
GtkWidget* create_confirmation (void);
