/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Admin (void);
GtkWidget* create_auth (void);
GtkWidget* create_inscription (void);
GtkWidget* create_etudiant (void);
GtkWidget* create_ajouterEtudiant (void);
GtkWidget* create_recherchee (void);
GtkWidget* create_reclam (void);
GtkWidget* create_resto (void);
GtkWidget* create_foyer (void);
GtkWidget* create_af_hebergement (void);
GtkWidget* create_mod_hebergement (void);
GtkWidget* create_recherche (void);
GtkWidget* create_aj_hebergement (void);
GtkWidget* create_event (void);
GtkWidget* create_Espace_technicien (void);
GtkWidget* create_Ajouter_un_capteur (void);
GtkWidget* create_modifier_un_capteur (void);
GtkWidget* create_dash (void);
GtkWidget* create_af_alarme (void);
GtkWidget* create_debit (void);
GtkWidget* create_nutr (void);
