/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Admin;
  GtkWidget *auth;
  GtkWidget *inscription;
  GtkWidget *window1;
  GtkWidget *window2;
  GtkWidget *window3;
  GtkWidget *window4;
  GtkWidget *window5;
  GtkWidget *window6;
  GtkWidget *etudiant;
  GtkWidget *ajouterEtudiant;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //Admin = create_Admin ();
  //gtk_widget_show (Admin);
  auth = create_auth ();
  gtk_widget_show (auth);
  //inscription = create_inscription ();
  //gtk_widget_show (inscription);
  //window1 = create_window1 ();
  //gtk_widget_show (window1);
  //window2 = create_window2 ();
  //gtk_widget_show (window2);  
//window3 = create_window3 ();
  //gtk_widget_show (window3);  
//window4 = create_window4 ();
  //gtk_widget_show (window4);  
//window5 = create_window5 ();
  //gtk_widget_show (window5);  
//window6 = create_window6 ();
  //gtk_widget_show (window6);

//etudiant = create_etudiant ();
//gtk_widget_show (etudiant);
//ajouterEtudiant = create_ajouterEtudiant ();
//gtk_widget_show (ajouterEtudiant);


  gtk_main ();
  return 0;
}

