/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dashboard_hebergement (void);
GtkWidget* create_af_alarme (void);
GtkWidget* create_af_hebergement (void);
GtkWidget* create_mod_hebergement (void);
GtkWidget* create_aj_hebergement (void);
GtkWidget* create_recherche (void);
