/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dashboard_hebergement (void)
{
  GtkWidget *dashboard_hebergement;
  GtkWidget *fixed1dr;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button3;
  GtkWidget *button2;
  GtkWidget *image9dr;
  GtkWidget *button1;

  dashboard_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (dashboard_hebergement, 600, 600);
  gtk_window_set_title (GTK_WINDOW (dashboard_hebergement), _("Gestion des \303\251tudiants h\303\251berg\303\251s"));
  gtk_window_set_position (GTK_WINDOW (dashboard_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (dashboard_hebergement), FALSE);

  fixed1dr = gtk_fixed_new ();
  gtk_widget_show (fixed1dr);
  gtk_container_add (GTK_CONTAINER (dashboard_hebergement), fixed1dr);

  button4 = gtk_button_new_with_mnemonic (_("Liste des alarmes entre 00h et 06h"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1dr), button4, 160, 504);
  gtk_widget_set_size_request (button4, 304, 72);

  button5 = gtk_button_new_with_mnemonic (_("Chercher un \303\251tudiant h\303\251berg\303\251"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1dr), button5, 160, 408);
  gtk_widget_set_size_request (button5, 304, 72);

  button3 = gtk_button_new_with_mnemonic (_("Afficher les \303\251tudiants h\303\251berg\303\251s"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1dr), button3, 160, 304);
  gtk_widget_set_size_request (button3, 304, 72);

  button2 = gtk_button_new_with_mnemonic (_("Modifier un \303\251tudiant h\303\251berg\303\251"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1dr), button2, 160, 192);
  gtk_widget_set_size_request (button2, 304, 80);

  image9dr = create_pixmap (dashboard_hebergement, "logos.png");
  gtk_widget_show (image9dr);
  gtk_fixed_put (GTK_FIXED (fixed1dr), image9dr, 0, 0);
  gtk_widget_set_size_request (image9dr, 220, 115);

  button1 = gtk_button_new_with_mnemonic (_("Ajouter un \303\251tudiant h\303\251berg\303\251"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1dr), button1, 160, 104);
  gtk_widget_set_size_request (button1, 296, 72);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button_4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button_3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button_2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button_1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dashboard_hebergement, dashboard_hebergement, "dashboard_hebergement");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, fixed1dr, "fixed1dr");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button4, "button4");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button5, "button5");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button3, "button3");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button2, "button2");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, image9dr, "image9dr");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button1, "button1");

  return dashboard_hebergement;
}

GtkWidget*
create_af_alarme (void)
{
  GtkWidget *af_alarme;
  GtkWidget *fixed2dr;
  GtkWidget *eventbox1dr;
  GtkWidget *alignment1dr;
  GtkWidget *eventbox2dr;
  GtkWidget *scrolledwindow1dr;
  GtkWidget *alignment2dr;
  GtkWidget *treeview_alarme;
  GtkWidget *image10dr;
  GtkWidget *label1dr;
  GtkWidget *button_af_alarme;
  GtkWidget *alignment3dr;
  GtkWidget *hbox1dr;
  GtkWidget *image1dr;
  GtkWidget *label2dr;

  af_alarme = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (af_alarme, 824, 600);
  gtk_window_set_title (GTK_WINDOW (af_alarme), _("Liste des alarmes entre 00h et 06h"));
  gtk_window_set_position (GTK_WINDOW (af_alarme), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (af_alarme), FALSE);

  fixed2dr = gtk_fixed_new ();
  gtk_widget_show (fixed2dr);
  gtk_container_add (GTK_CONTAINER (af_alarme), fixed2dr);

  eventbox1dr = gtk_event_box_new ();
  gtk_widget_show (eventbox1dr);
  gtk_fixed_put (GTK_FIXED (fixed2dr), eventbox1dr, 128, 112);
  gtk_widget_set_size_request (eventbox1dr, 568, 304);

  alignment1dr = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1dr);
  gtk_container_add (GTK_CONTAINER (eventbox1dr), alignment1dr);

  eventbox2dr = gtk_event_box_new ();
  gtk_widget_show (eventbox2dr);
  gtk_container_add (GTK_CONTAINER (alignment1dr), eventbox2dr);

  scrolledwindow1dr = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1dr);
  gtk_container_add (GTK_CONTAINER (eventbox2dr), scrolledwindow1dr);
  gtk_widget_set_size_request (scrolledwindow1dr, 568, 304);

  alignment2dr = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2dr);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1dr), alignment2dr);

  treeview_alarme = gtk_tree_view_new ();
  gtk_widget_show (treeview_alarme);
  gtk_container_add (GTK_CONTAINER (alignment2dr), treeview_alarme);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview_alarme), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview_alarme), TRUE);

  image10dr = create_pixmap (af_alarme, "logos.png");
  gtk_widget_show (image10dr);
  gtk_fixed_put (GTK_FIXED (fixed2dr), image10dr, 8, 0);
  gtk_widget_set_size_request (image10dr, 220, 115);

  label1dr = gtk_label_new (_("<b><span color='red'>Liste des alarmes entre 00h et 06h</span></b>"));
  gtk_widget_show (label1dr);
  gtk_fixed_put (GTK_FIXED (fixed2dr), label1dr, 280, 48);
  gtk_widget_set_size_request (label1dr, 280, 56);
  gtk_label_set_use_markup (GTK_LABEL (label1dr), TRUE);

  button_af_alarme = gtk_button_new ();
  gtk_widget_show (button_af_alarme);
  gtk_fixed_put (GTK_FIXED (fixed2dr), button_af_alarme, 368, 432);
  gtk_widget_set_size_request (button_af_alarme, 112, 48);

  alignment3dr = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3dr);
  gtk_container_add (GTK_CONTAINER (button_af_alarme), alignment3dr);

  hbox1dr = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1dr);
  gtk_container_add (GTK_CONTAINER (alignment3dr), hbox1dr);

  image1dr = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1dr);
  gtk_box_pack_start (GTK_BOX (hbox1dr), image1dr, FALSE, FALSE, 0);

  label2dr = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label2dr);
  gtk_box_pack_start (GTK_BOX (hbox1dr), label2dr, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_af_alarme, "clicked",
                    G_CALLBACK (on_button_af_alarme_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (af_alarme, af_alarme, "af_alarme");
  GLADE_HOOKUP_OBJECT (af_alarme, fixed2dr, "fixed2dr");
  GLADE_HOOKUP_OBJECT (af_alarme, eventbox1dr, "eventbox1dr");
  GLADE_HOOKUP_OBJECT (af_alarme, alignment1dr, "alignment1dr");
  GLADE_HOOKUP_OBJECT (af_alarme, eventbox2dr, "eventbox2dr");
  GLADE_HOOKUP_OBJECT (af_alarme, scrolledwindow1dr, "scrolledwindow1dr");
  GLADE_HOOKUP_OBJECT (af_alarme, alignment2dr, "alignment2dr");
  GLADE_HOOKUP_OBJECT (af_alarme, treeview_alarme, "treeview_alarme");
  GLADE_HOOKUP_OBJECT (af_alarme, image10dr, "image10dr");
  GLADE_HOOKUP_OBJECT (af_alarme, label1dr, "label1dr");
  GLADE_HOOKUP_OBJECT (af_alarme, button_af_alarme, "button_af_alarme");
  GLADE_HOOKUP_OBJECT (af_alarme, alignment3dr, "alignment3dr");
  GLADE_HOOKUP_OBJECT (af_alarme, hbox1dr, "hbox1dr");
  GLADE_HOOKUP_OBJECT (af_alarme, image1dr, "image1dr");
  GLADE_HOOKUP_OBJECT (af_alarme, label2dr, "label2dr");

  return af_alarme;
}

GtkWidget*
create_af_hebergement (void)
{
  GtkWidget *af_hebergement;
  GtkWidget *fixed3dr;
  GtkWidget *scrolledwindow2dr;
  GtkWidget *treeview_hebergement;
  GtkWidget *button_af;
  GtkWidget *alignment13dr;
  GtkWidget *hbox9dr;
  GtkWidget *image11dr;
  GtkWidget *label40dr;
  GtkWidget *label3dr;
  GtkWidget *image12dr;

  af_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (af_hebergement, 824, 550);
  gtk_window_set_title (GTK_WINDOW (af_hebergement), _("Liste des \303\251tudiants h\303\251berg\303\251s"));
  gtk_window_set_position (GTK_WINDOW (af_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (af_hebergement), FALSE);

  fixed3dr = gtk_fixed_new ();
  gtk_widget_show (fixed3dr);
  gtk_container_add (GTK_CONTAINER (af_hebergement), fixed3dr);

  scrolledwindow2dr = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2dr);
  gtk_fixed_put (GTK_FIXED (fixed3dr), scrolledwindow2dr, 48, 120);
  gtk_widget_set_size_request (scrolledwindow2dr, 752, 360);

  treeview_hebergement = gtk_tree_view_new ();
  gtk_widget_show (treeview_hebergement);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2dr), treeview_hebergement);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview_hebergement), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview_hebergement), TRUE);

  button_af = gtk_button_new ();
  gtk_widget_show (button_af);
  gtk_fixed_put (GTK_FIXED (fixed3dr), button_af, 368, 488);
  gtk_widget_set_size_request (button_af, 112, 48);

  alignment13dr = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13dr);
  gtk_container_add (GTK_CONTAINER (button_af), alignment13dr);

  hbox9dr = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9dr);
  gtk_container_add (GTK_CONTAINER (alignment13dr), hbox9dr);

  image11dr = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11dr);
  gtk_box_pack_start (GTK_BOX (hbox9dr), image11dr, FALSE, FALSE, 0);

  label40dr = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label40dr);
  gtk_box_pack_start (GTK_BOX (hbox9dr), label40dr, FALSE, FALSE, 0);

  label3dr = gtk_label_new (_("<b><span color='red'>Liste des \303\251tudiants h\303\251berg\303\251s</span></b>"));
  gtk_widget_show (label3dr);
  gtk_fixed_put (GTK_FIXED (fixed3dr), label3dr, 288, 56);
  gtk_widget_set_size_request (label3dr, 280, 56);
  gtk_label_set_use_markup (GTK_LABEL (label3dr), TRUE);

  image12dr = create_pixmap (af_hebergement, "logos.png");
  gtk_widget_show (image12dr);
  gtk_fixed_put (GTK_FIXED (fixed3dr), image12dr, 0, 0);
  gtk_widget_set_size_request (image12dr, 220, 115);

  g_signal_connect ((gpointer) treeview_hebergement, "row_activated",
                    G_CALLBACK (on_treeview_hebergement_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_af, "clicked",
                    G_CALLBACK (on_button_af_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (af_hebergement, af_hebergement, "af_hebergement");
  GLADE_HOOKUP_OBJECT (af_hebergement, fixed3dr, "fixed3dr");
  GLADE_HOOKUP_OBJECT (af_hebergement, scrolledwindow2dr, "scrolledwindow2dr");
  GLADE_HOOKUP_OBJECT (af_hebergement, treeview_hebergement, "treeview_hebergement");
  GLADE_HOOKUP_OBJECT (af_hebergement, button_af, "button_af");
  GLADE_HOOKUP_OBJECT (af_hebergement, alignment13dr, "alignment13dr");
  GLADE_HOOKUP_OBJECT (af_hebergement, hbox9dr, "hbox9dr");
  GLADE_HOOKUP_OBJECT (af_hebergement, image11dr, "image11dr");
  GLADE_HOOKUP_OBJECT (af_hebergement, label40dr, "label40dr");
  GLADE_HOOKUP_OBJECT (af_hebergement, label3dr, "label3dr");
  GLADE_HOOKUP_OBJECT (af_hebergement, image12dr, "image12dr");

  return af_hebergement;
}

GtkWidget*
create_mod_hebergement (void)
{
  GtkWidget *mod_hebergement;
  GtkWidget *fixed4dr;
  GtkWidget *mod5;
  GtkWidget *mod2;
  GtkWidget *mod3;
  GtkWidget *mod1;
  GtkWidget *mod6;
  GtkWidget *label5dr;
  GtkWidget *label6dr;
  GtkWidget *label10dr;
  GtkWidget *button_mod;
  GtkWidget *alignment8dr;
  GtkWidget *hbox4dr;
  GtkWidget *image4dr;
  GtkWidget *label12dr;
  GtkWidget *check_id;
  GtkWidget *alignment7dr;
  GtkWidget *hbox3dr;
  GtkWidget *image3dr;
  GtkWidget *label11dr;
  GtkWidget *mod4;
  GtkWidget *label9dr;
  GtkWidget *label8dr;
  GtkWidget *label22dr;
  GtkWidget *modA;
  GSList *modA_group = NULL;
  GtkWidget *modB;
  GtkWidget *modC;
  GtkWidget *label36dr;
  GtkWidget *label37dr;
  GtkObject *mod7_adj;
  GtkWidget *mod7;
  GtkWidget *image13dr;

  mod_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mod_hebergement, 784, 720);
  gtk_window_set_title (GTK_WINDOW (mod_hebergement), _("Modifier un \303\251tudiant h\303\251berg\303\251"));
  gtk_window_set_position (GTK_WINDOW (mod_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (mod_hebergement), FALSE);

  fixed4dr = gtk_fixed_new ();
  gtk_widget_show (fixed4dr);
  gtk_container_add (GTK_CONTAINER (mod_hebergement), fixed4dr);

  mod5 = gtk_entry_new ();
  gtk_widget_show (mod5);
  gtk_fixed_put (GTK_FIXED (fixed4dr), mod5, 168, 512);
  gtk_widget_set_size_request (mod5, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod5), 8226);

  mod2 = gtk_entry_new ();
  gtk_widget_show (mod2);
  gtk_fixed_put (GTK_FIXED (fixed4dr), mod2, 176, 272);
  gtk_widget_set_size_request (mod2, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod2), 8226);

  mod3 = gtk_entry_new ();
  gtk_widget_show (mod3);
  gtk_fixed_put (GTK_FIXED (fixed4dr), mod3, 176, 328);
  gtk_widget_set_size_request (mod3, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod3), 8226);

  mod1 = gtk_entry_new ();
  gtk_widget_show (mod1);
  gtk_fixed_put (GTK_FIXED (fixed4dr), mod1, 296, 160);
  gtk_widget_set_size_request (mod1, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod1), 8226);

  mod6 = gtk_entry_new ();
  gtk_widget_show (mod6);
  gtk_fixed_put (GTK_FIXED (fixed4dr), mod6, 168, 576);
  gtk_widget_set_size_request (mod6, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod6), 8226);

  label5dr = gtk_label_new (_("Email :"));
  gtk_widget_show (label5dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label5dr, 64, 584);
  gtk_widget_set_size_request (label5dr, 57, 17);

  label6dr = gtk_label_new (_("Tel :"));
  gtk_widget_show (label6dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label6dr, 72, 528);
  gtk_widget_set_size_request (label6dr, 56, 16);

  label10dr = gtk_label_new (_("ID :"));
  gtk_widget_show (label10dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label10dr, 184, 168);
  gtk_widget_set_size_request (label10dr, 40, 16);

  button_mod = gtk_button_new ();
  gtk_widget_show (button_mod);
  gtk_fixed_put (GTK_FIXED (fixed4dr), button_mod, 352, 656);
  gtk_widget_set_size_request (button_mod, 120, 48);

  alignment8dr = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8dr);
  gtk_container_add (GTK_CONTAINER (button_mod), alignment8dr);

  hbox4dr = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4dr);
  gtk_container_add (GTK_CONTAINER (alignment8dr), hbox4dr);

  image4dr = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4dr);
  gtk_box_pack_start (GTK_BOX (hbox4dr), image4dr, FALSE, FALSE, 0);

  label12dr = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label12dr);
  gtk_box_pack_start (GTK_BOX (hbox4dr), label12dr, FALSE, FALSE, 0);

  check_id = gtk_button_new ();
  gtk_widget_show (check_id);
  gtk_fixed_put (GTK_FIXED (fixed4dr), check_id, 528, 152);
  gtk_widget_set_size_request (check_id, 104, 48);

  alignment7dr = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7dr);
  gtk_container_add (GTK_CONTAINER (check_id), alignment7dr);

  hbox3dr = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3dr);
  gtk_container_add (GTK_CONTAINER (alignment7dr), hbox3dr);

  image3dr = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3dr);
  gtk_box_pack_start (GTK_BOX (hbox3dr), image3dr, FALSE, FALSE, 0);

  label11dr = gtk_label_new_with_mnemonic (_("V\303\251rifier"));
  gtk_widget_show (label11dr);
  gtk_box_pack_start (GTK_BOX (hbox3dr), label11dr, FALSE, FALSE, 0);

  mod4 = gtk_combo_box_new_text ();
  gtk_widget_show (mod4);
  gtk_fixed_put (GTK_FIXED (fixed4dr), mod4, 168, 448);
  gtk_widget_set_size_request (mod4, 176, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod4), _("Individuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod4), _("Double"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod4), _("Triple"));

  label9dr = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label9dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label9dr, 64, 272);
  gtk_widget_set_size_request (label9dr, 80, 24);

  label8dr = gtk_label_new (_("Nom :"));
  gtk_widget_show (label8dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label8dr, 72, 336);
  gtk_widget_set_size_request (label8dr, 64, 16);

  label22dr = gtk_label_new (_("Bloc :"));
  gtk_widget_show (label22dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label22dr, 72, 392);
  gtk_widget_set_size_request (label22dr, 64, 16);

  modA = gtk_radio_button_new_with_mnemonic (NULL, _("A"));
  gtk_widget_show (modA);
  gtk_fixed_put (GTK_FIXED (fixed4dr), modA, 192, 392);
  gtk_widget_set_size_request (modA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modA), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modA));

  modB = gtk_radio_button_new_with_mnemonic (NULL, _("B"));
  gtk_widget_show (modB);
  gtk_fixed_put (GTK_FIXED (fixed4dr), modB, 352, 392);
  gtk_widget_set_size_request (modB, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modB), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modB));

  modC = gtk_radio_button_new_with_mnemonic (NULL, _("C"));
  gtk_widget_show (modC);
  gtk_fixed_put (GTK_FIXED (fixed4dr), modC, 528, 392);
  gtk_widget_set_size_request (modC, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modC), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modC));

  label36dr = gtk_label_new (_("Type chambre :"));
  gtk_widget_show (label36dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label36dr, 8, 456);
  gtk_widget_set_size_request (label36dr, 112, 24);

  label37dr = gtk_label_new (_("Num chambre :"));
  gtk_widget_show (label37dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), label37dr, 368, 456);
  gtk_widget_set_size_request (label37dr, 112, 24);

  mod7_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  mod7 = gtk_spin_button_new (GTK_ADJUSTMENT (mod7_adj), 1, 0);
  gtk_widget_show (mod7);
  gtk_fixed_put (GTK_FIXED (fixed4dr), mod7, 504, 456);
  gtk_widget_set_size_request (mod7, 60, 27);

  image13dr = create_pixmap (mod_hebergement, "logos.png");
  gtk_widget_show (image13dr);
  gtk_fixed_put (GTK_FIXED (fixed4dr), image13dr, 0, 0);
  gtk_widget_set_size_request (image13dr, 220, 115);

  g_signal_connect ((gpointer) button_mod, "clicked",
                    G_CALLBACK (on_button_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) check_id, "clicked",
                    G_CALLBACK (on_check_id_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod_hebergement, mod_hebergement, "mod_hebergement");
  GLADE_HOOKUP_OBJECT (mod_hebergement, fixed4dr, "fixed4dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod5, "mod5");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod2, "mod2");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod3, "mod3");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod1, "mod1");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod6, "mod6");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label5dr, "label5dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label6dr, "label6dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label10dr, "label10dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, button_mod, "button_mod");
  GLADE_HOOKUP_OBJECT (mod_hebergement, alignment8dr, "alignment8dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, hbox4dr, "hbox4dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, image4dr, "image4dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label12dr, "label12dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, check_id, "check_id");
  GLADE_HOOKUP_OBJECT (mod_hebergement, alignment7dr, "alignment7dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, hbox3dr, "hbox3dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, image3dr, "image3dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label11dr, "label11dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod4, "mod4");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label9dr, "label9dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label8dr, "label8dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label22dr, "label22dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, modA, "modA");
  GLADE_HOOKUP_OBJECT (mod_hebergement, modB, "modB");
  GLADE_HOOKUP_OBJECT (mod_hebergement, modC, "modC");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label36dr, "label36dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label37dr, "label37dr");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod7, "mod7");
  GLADE_HOOKUP_OBJECT (mod_hebergement, image13dr, "image13dr");

  return mod_hebergement;
}

GtkWidget*
create_aj_hebergement (void)
{
  GtkWidget *aj_hebergement;
  GtkWidget *fixed5dr;
  GtkWidget *aj5;
  GtkWidget *ajc;
  GtkWidget *aj2;
  GtkWidget *aj3;
  GtkWidget *aj6;
  GtkWidget *aj1;
  GtkObject *aj7_adj;
  GtkWidget *aj7;
  GtkWidget *button_aj;
  GtkWidget *alignment10dr;
  GtkWidget *hbox6dr;
  GtkWidget *image6dr;
  GtkWidget *label21dr;
  GtkWidget *label16dr;
  GtkWidget *label17dr;
  GtkWidget *label18dr;
  GtkWidget *aj4;
  GtkWidget *label23dr;
  GtkWidget *ajA;
  GSList *ajA_group = NULL;
  GtkWidget *label35dr;
  GtkWidget *ajB;
  GtkWidget *ajC;
  GtkWidget *label13dr;
  GtkWidget *label19dr;
  GtkWidget *label14dr;
  GtkWidget *image14dr;
  GtkWidget *label20dr;

  aj_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (aj_hebergement, 784, 720);
  gtk_window_set_title (GTK_WINDOW (aj_hebergement), _("Ajouter un \303\251tudiant h\303\251berg\303\251"));
  gtk_window_set_position (GTK_WINDOW (aj_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (aj_hebergement), FALSE);

  fixed5dr = gtk_fixed_new ();
  gtk_widget_show (fixed5dr);
  gtk_container_add (GTK_CONTAINER (aj_hebergement), fixed5dr);

  aj5 = gtk_entry_new ();
  gtk_widget_show (aj5);
  gtk_fixed_put (GTK_FIXED (fixed5dr), aj5, 160, 600);
  gtk_widget_set_size_request (aj5, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj5), 8226);

  ajc = gtk_calendar_new ();
  gtk_widget_show (ajc);
  gtk_fixed_put (GTK_FIXED (fixed5dr), ajc, 168, 296);
  gtk_widget_set_size_request (ajc, 216, 184);
  gtk_calendar_display_options (GTK_CALENDAR (ajc),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  aj2 = gtk_entry_new ();
  gtk_widget_show (aj2);
  gtk_fixed_put (GTK_FIXED (fixed5dr), aj2, 176, 208);
  gtk_widget_set_size_request (aj2, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj2), 8226);

  aj3 = gtk_entry_new ();
  gtk_widget_show (aj3);
  gtk_fixed_put (GTK_FIXED (fixed5dr), aj3, 176, 248);
  gtk_widget_set_size_request (aj3, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj3), 8226);

  aj6 = gtk_entry_new ();
  gtk_widget_show (aj6);
  gtk_fixed_put (GTK_FIXED (fixed5dr), aj6, 160, 648);
  gtk_widget_set_size_request (aj6, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj6), 8226);

  aj1 = gtk_entry_new ();
  gtk_widget_show (aj1);
  gtk_fixed_put (GTK_FIXED (fixed5dr), aj1, 176, 160);
  gtk_widget_set_size_request (aj1, 136, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj1), 8226);

  aj7_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  aj7 = gtk_spin_button_new (GTK_ADJUSTMENT (aj7_adj), 1, 0);
  gtk_widget_show (aj7);
  gtk_fixed_put (GTK_FIXED (fixed5dr), aj7, 512, 552);
  gtk_widget_set_size_request (aj7, 60, 27);

  button_aj = gtk_button_new ();
  gtk_widget_show (button_aj);
  gtk_fixed_put (GTK_FIXED (fixed5dr), button_aj, 544, 224);
  gtk_widget_set_size_request (button_aj, 120, 48);

  alignment10dr = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10dr);
  gtk_container_add (GTK_CONTAINER (button_aj), alignment10dr);

  hbox6dr = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6dr);
  gtk_container_add (GTK_CONTAINER (alignment10dr), hbox6dr);

  image6dr = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6dr);
  gtk_box_pack_start (GTK_BOX (hbox6dr), image6dr, FALSE, FALSE, 0);

  label21dr = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label21dr);
  gtk_box_pack_start (GTK_BOX (hbox6dr), label21dr, FALSE, FALSE, 0);

  label16dr = gtk_label_new (_("Email :"));
  gtk_widget_show (label16dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label16dr, 64, 664);
  gtk_widget_set_size_request (label16dr, 57, 17);

  label17dr = gtk_label_new (_("Tel :"));
  gtk_widget_show (label17dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label17dr, 64, 616);
  gtk_widget_set_size_request (label17dr, 56, 16);

  label18dr = gtk_label_new (_("Type chambre :"));
  gtk_widget_show (label18dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label18dr, 32, 552);
  gtk_widget_set_size_request (label18dr, 112, 24);

  aj4 = gtk_combo_box_new_text ();
  gtk_widget_show (aj4);
  gtk_fixed_put (GTK_FIXED (fixed5dr), aj4, 168, 544);
  gtk_widget_set_size_request (aj4, 176, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("Individuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("Double"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("Triple"));

  label23dr = gtk_label_new (_("Bloc :"));
  gtk_widget_show (label23dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label23dr, 32, 504);
  gtk_widget_set_size_request (label23dr, 112, 24);

  ajA = gtk_radio_button_new_with_mnemonic (NULL, _("A"));
  gtk_widget_show (ajA);
  gtk_fixed_put (GTK_FIXED (fixed5dr), ajA, 184, 504);
  gtk_widget_set_size_request (ajA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajA), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajA));

  label35dr = gtk_label_new (_("Num chambre :"));
  gtk_widget_show (label35dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label35dr, 368, 552);
  gtk_widget_set_size_request (label35dr, 112, 24);

  ajB = gtk_radio_button_new_with_mnemonic (NULL, _("B"));
  gtk_widget_show (ajB);
  gtk_fixed_put (GTK_FIXED (fixed5dr), ajB, 328, 504);
  gtk_widget_set_size_request (ajB, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajB), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajB));

  ajC = gtk_radio_button_new_with_mnemonic (NULL, _("C"));
  gtk_widget_show (ajC);
  gtk_fixed_put (GTK_FIXED (fixed5dr), ajC, 464, 504);
  gtk_widget_set_size_request (ajC, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajC), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajC));

  label13dr = gtk_label_new (_("Nom :"));
  gtk_widget_show (label13dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label13dr, 64, 256);
  gtk_widget_set_size_request (label13dr, 64, 16);

  label19dr = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label19dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label19dr, 56, 208);
  gtk_widget_set_size_request (label19dr, 80, 24);

  label14dr = gtk_label_new (_("ID :"));
  gtk_widget_show (label14dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label14dr, 80, 176);
  gtk_widget_set_size_request (label14dr, 40, 16);

  image14dr = create_pixmap (aj_hebergement, "logos.png");
  gtk_widget_show (image14dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), image14dr, 0, 8);
  gtk_widget_set_size_request (image14dr, 220, 115);

  label20dr = gtk_label_new (_("Date d'h\303\251b\303\251rgement :"));
  gtk_widget_show (label20dr);
  gtk_fixed_put (GTK_FIXED (fixed5dr), label20dr, 8, 296);
  gtk_widget_set_size_request (label20dr, 152, 32);

  g_signal_connect ((gpointer) button_aj, "clicked",
                    G_CALLBACK (on_button_aj_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aj_hebergement, aj_hebergement, "aj_hebergement");
  GLADE_HOOKUP_OBJECT (aj_hebergement, fixed5dr, "fixed5dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj5, "aj5");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajc, "ajc");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj2, "aj2");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj3, "aj3");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj6, "aj6");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj1, "aj1");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj7, "aj7");
  GLADE_HOOKUP_OBJECT (aj_hebergement, button_aj, "button_aj");
  GLADE_HOOKUP_OBJECT (aj_hebergement, alignment10dr, "alignment10dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, hbox6dr, "hbox6dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, image6dr, "image6dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label21dr, "label21dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label16dr, "label16dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label17dr, "label17dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label18dr, "label18dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj4, "aj4");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label23dr, "label23dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajA, "ajA");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label35dr, "label35dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajB, "ajB");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajC, "ajC");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label13dr, "label13dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label19dr, "label19dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label14dr, "label14dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, image14dr, "image14dr");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label20dr, "label20dr");

  return aj_hebergement;
}

GtkWidget*
create_recherche (void)
{
  GtkWidget *recherche;
  GtkWidget *fixed6dr;
  GtkWidget *r1;
  GtkWidget *label24dr;
  GtkWidget *label25dr;
  GtkWidget *label32dr;
  GtkWidget *label34dr;
  GtkWidget *r3;
  GtkWidget *r4;
  GtkWidget *r5;
  GtkWidget *r6;
  GtkWidget *r7;
  GtkWidget *chercher;
  GtkWidget *alignment12;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label33;
  GtkWidget *label30dr;
  GtkWidget *label31dr;
  GtkWidget *r8;
  GtkWidget *label38dr;
  GtkWidget *label39dr;
  GtkWidget *r9;
  GtkWidget *label27dr;
  GtkWidget *image15dr;
  GtkWidget *r2;

  recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (recherche, 784, 720);
  gtk_window_set_title (GTK_WINDOW (recherche), _("Chercher un \303\251tudiant h\303\251berg\303\251"));
  gtk_window_set_position (GTK_WINDOW (recherche), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (recherche), FALSE);

  fixed6dr = gtk_fixed_new ();
  gtk_widget_show (fixed6dr);
  gtk_container_add (GTK_CONTAINER (recherche), fixed6dr);

  r1 = gtk_entry_new ();
  gtk_widget_show (r1);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r1, 336, 64);
  gtk_widget_set_size_request (r1, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (r1), 8226);

  label24dr = gtk_label_new (_("Email :"));
  gtk_widget_show (label24dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label24dr, 64, 584);
  gtk_widget_set_size_request (label24dr, 57, 17);

  label25dr = gtk_label_new (_("Tel :"));
  gtk_widget_show (label25dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label25dr, 72, 528);
  gtk_widget_set_size_request (label25dr, 56, 16);

  label32dr = gtk_label_new (_("Bloc :"));
  gtk_widget_show (label32dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label32dr, 72, 392);
  gtk_widget_set_size_request (label32dr, 64, 16);

  label34dr = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label34dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label34dr, 24, 320);
  gtk_widget_set_size_request (label34dr, 144, 16);

  r3 = gtk_label_new ("");
  gtk_widget_show (r3);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r3, 224, 248);
  gtk_widget_set_size_request (r3, 232, 32);

  r4 = gtk_label_new ("");
  gtk_widget_show (r4);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r4, 224, 312);
  gtk_widget_set_size_request (r4, 232, 32);

  r5 = gtk_label_new ("");
  gtk_widget_show (r5);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r5, 224, 384);
  gtk_widget_set_size_request (r5, 232, 32);

  r6 = gtk_label_new ("");
  gtk_widget_show (r6);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r6, 224, 456);
  gtk_widget_set_size_request (r6, 232, 32);

  r7 = gtk_label_new ("");
  gtk_widget_show (r7);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r7, 224, 520);
  gtk_widget_set_size_request (r7, 232, 32);

  chercher = gtk_button_new ();
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed6dr), chercher, 608, 56);
  gtk_widget_set_size_request (chercher, 104, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (chercher), alignment12);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox8), label33, FALSE, FALSE, 0);

  label30dr = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label30dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label30dr, 64, 184);
  gtk_widget_set_size_request (label30dr, 80, 24);

  label31dr = gtk_label_new (_("Nom :"));
  gtk_widget_show (label31dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label31dr, 72, 256);
  gtk_widget_set_size_request (label31dr, 64, 16);

  r8 = gtk_label_new ("");
  gtk_widget_show (r8);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r8, 224, 576);
  gtk_widget_set_size_request (r8, 232, 32);

  label38dr = gtk_label_new (_("Type chambre :"));
  gtk_widget_show (label38dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label38dr, 16, 464);
  gtk_widget_set_size_request (label38dr, 112, 24);

  label39dr = gtk_label_new (_("Num chambre :"));
  gtk_widget_show (label39dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label39dr, 456, 464);
  gtk_widget_set_size_request (label39dr, 112, 24);

  r9 = gtk_label_new ("");
  gtk_widget_show (r9);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r9, 624, 464);
  gtk_widget_set_size_request (r9, 49, 17);

  label27dr = gtk_label_new (_("ID :"));
  gtk_widget_show (label27dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), label27dr, 256, 72);
  gtk_widget_set_size_request (label27dr, 40, 16);

  image15dr = create_pixmap (recherche, "logos.png");
  gtk_widget_show (image15dr);
  gtk_fixed_put (GTK_FIXED (fixed6dr), image15dr, 0, 0);
  gtk_widget_set_size_request (image15dr, 220, 115);

  r2 = gtk_label_new ("");
  gtk_widget_show (r2);
  gtk_fixed_put (GTK_FIXED (fixed6dr), r2, 224, 184);
  gtk_widget_set_size_request (r2, 232, 32);

  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (recherche, fixed6dr, "fixed6dr");
  GLADE_HOOKUP_OBJECT (recherche, r1, "r1");
  GLADE_HOOKUP_OBJECT (recherche, label24dr, "label24dr");
  GLADE_HOOKUP_OBJECT (recherche, label25dr, "label25dr");
  GLADE_HOOKUP_OBJECT (recherche, label32dr, "label32dr");
  GLADE_HOOKUP_OBJECT (recherche, label34dr, "label34dr");
  GLADE_HOOKUP_OBJECT (recherche, r3, "r3");
  GLADE_HOOKUP_OBJECT (recherche, r4, "r4");
  GLADE_HOOKUP_OBJECT (recherche, r5, "r5");
  GLADE_HOOKUP_OBJECT (recherche, r6, "r6");
  GLADE_HOOKUP_OBJECT (recherche, r7, "r7");
  GLADE_HOOKUP_OBJECT (recherche, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (recherche, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (recherche, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (recherche, image8, "image8");
  GLADE_HOOKUP_OBJECT (recherche, label33, "label33");
  GLADE_HOOKUP_OBJECT (recherche, label30dr, "label30dr");
  GLADE_HOOKUP_OBJECT (recherche, label31dr, "label31dr");
  GLADE_HOOKUP_OBJECT (recherche, r8, "r8");
  GLADE_HOOKUP_OBJECT (recherche, label38dr, "label38dr");
  GLADE_HOOKUP_OBJECT (recherche, label39dr, "label39dr");
  GLADE_HOOKUP_OBJECT (recherche, r9, "r9");
  GLADE_HOOKUP_OBJECT (recherche, label27dr, "label27dr");
  GLADE_HOOKUP_OBJECT (recherche, image15dr, "image15dr");
  GLADE_HOOKUP_OBJECT (recherche, r2, "r2");

  return recherche;
}

