/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_reclam (void)
{
  GtkWidget *Gestion_reclam;
  GtkWidget *fixed4;
  GtkWidget *image89;
  GtkWidget *button7_quiter_ouv;
  GtkWidget *alignment74;
  GtkWidget *hbox74;
  GtkWidget *image79;
  GtkWidget *label315;
  GtkWidget *instagram;
  GtkWidget *image86;
  GtkWidget *facebook;
  GtkWidget *image85;
  GtkWidget *notebook3;
  GtkWidget *fixed15;
  GtkWidget *treeview5;
  GtkWidget *label238;
  GtkWidget *supp_tree_ch;
  GtkWidget *alignment51;
  GtkWidget *hbox51;
  GtkWidget *image54;
  GtkWidget *label382;
  GtkWidget *modifier_ch;
  GtkWidget *alignment50;
  GtkWidget *hbox50;
  GtkWidget *image53;
  GtkWidget *label381;
  GtkWidget *label373;
  GtkWidget *button56;
  GtkWidget *alignment78;
  GtkWidget *hbox78;
  GtkWidget *image87;
  GtkWidget *label383;
  GtkWidget *label372;
  GtkWidget *fixed12;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label279;
  GtkWidget *button18;
  GtkWidget *checkbutton14_groupe;
  GtkWidget *checkbutton15_groupe;
  GtkWidget *label337;
  GtkWidget *label338;
  GtkWidget *radiobutton11_poste;
  GSList *radiobutton11_poste_group = NULL;
  GtkWidget *radiobutton12_poste;
  GtkWidget *button19;
  GtkWidget *button5_ok_;
  GtkWidget *alignment59;
  GtkWidget *hbox59;
  GtkWidget *image62;
  GtkWidget *label377;
  GtkWidget *label356;
  GtkWidget *label390;
  GtkWidget *label391;
  GtkWidget *label360;
  GtkWidget *label334;
  GtkWidget *label359;
  GtkWidget *label333;
  GtkWidget *label335;
  GtkWidget *combobox6;
  GtkWidget *label361;
  GtkWidget *label357;
  GtkWidget *label336;
  GtkWidget *label362;
  GtkWidget *label366;
  GtkWidget *ajou_ch;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label376;
  GtkWidget *label393;
  GtkWidget *label363;
  GtkWidget *label364;
  GtkWidget *label365;
  GtkWidget *label369;
  GtkWidget *fixed14;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry20;
  GtkWidget *label84;
  GtkWidget *label317;
  GtkWidget *rech_ch;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label379;
  GtkWidget *label394;
  GtkWidget *label384;
  GtkWidget *label387;
  GtkWidget *label386;
  GtkWidget *label389;
  GtkWidget *label358;
  GtkWidget *combobox7;
  GtkWidget *label385;
  GtkWidget *label354;
  GtkWidget *modi_ch;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label380;
  GtkWidget *calendar;
  GtkWidget *label371;
  GtkWidget *fixed13;
  GtkWidget *entry15;
  GtkWidget *label83;
  GtkWidget *label332;
  GtkWidget *supp_ch;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label378;
  GtkWidget *label392;
  GtkWidget *label370;

  Gestion_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_reclam), _("Gestion Reclamation"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Gestion_reclam), fixed4);

  image89 = create_pixmap (Gestion_reclam, "logos.png");
  gtk_widget_show (image89);
  gtk_fixed_put (GTK_FIXED (fixed4), image89, 0, 0);
  gtk_widget_set_size_request (image89, 264, 144);

  button7_quiter_ouv = gtk_button_new ();
  gtk_widget_show (button7_quiter_ouv);
  gtk_fixed_put (GTK_FIXED (fixed4), button7_quiter_ouv, 1296, 104);
  gtk_widget_set_size_request (button7_quiter_ouv, 96, 40);

  alignment74 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment74);
  gtk_container_add (GTK_CONTAINER (button7_quiter_ouv), alignment74);

  hbox74 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox74);
  gtk_container_add (GTK_CONTAINER (alignment74), hbox74);

  image79 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image79);
  gtk_box_pack_start (GTK_BOX (hbox74), image79, FALSE, FALSE, 0);

  label315 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> QUITER</span></b> "));
  gtk_widget_show (label315);
  gtk_box_pack_start (GTK_BOX (hbox74), label315, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label315), TRUE);

  instagram = gtk_button_new ();
  gtk_widget_show (instagram);
  gtk_fixed_put (GTK_FIXED (fixed4), instagram, 1320, 40);
  gtk_widget_set_size_request (instagram, 77, 44);

  image86 = create_pixmap (Gestion_reclam, "aaaaaaaaaaa.png");
  gtk_widget_show (image86);
  gtk_container_add (GTK_CONTAINER (instagram), image86);

  facebook = gtk_button_new ();
  gtk_widget_show (facebook);
  gtk_fixed_put (GTK_FIXED (fixed4), facebook, 1232, 40);
  gtk_widget_set_size_request (facebook, 74, 43);

  image85 = create_pixmap (Gestion_reclam, "button-facebookfinal.svg");
  gtk_widget_show (image85);
  gtk_container_add (GTK_CONTAINER (facebook), image85);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_fixed_put (GTK_FIXED (fixed4), notebook3, 0, 152);
  gtk_widget_set_size_request (notebook3, 1392, 736);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook3), GTK_POS_LEFT);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed15);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed15), treeview5, 8, 56);
  gtk_widget_set_size_request (treeview5, 976, 456);

  label238 = gtk_label_new ("");
  gtk_widget_show (label238);
  gtk_fixed_put (GTK_FIXED (fixed15), label238, 640, 496);
  gtk_widget_set_size_request (label238, 281, 41);

  supp_tree_ch = gtk_button_new ();
  gtk_widget_show (supp_tree_ch);
  gtk_fixed_put (GTK_FIXED (fixed15), supp_tree_ch, 1000, 176);
  gtk_widget_set_size_request (supp_tree_ch, 122, 45);

  alignment51 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment51);
  gtk_container_add (GTK_CONTAINER (supp_tree_ch), alignment51);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment51), hbox51);

  image54 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox51), image54, FALSE, FALSE, 0);

  label382 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Supprimer</span></b>"));
  gtk_widget_show (label382);
  gtk_box_pack_start (GTK_BOX (hbox51), label382, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label382, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label382), TRUE);

  modifier_ch = gtk_button_new ();
  gtk_widget_show (modifier_ch);
  gtk_fixed_put (GTK_FIXED (fixed15), modifier_ch, 1000, 112);
  gtk_widget_set_size_request (modifier_ch, 120, 48);

  alignment50 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment50);
  gtk_container_add (GTK_CONTAINER (modifier_ch), alignment50);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment50), hbox50);

  image53 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox50), image53, FALSE, FALSE, 0);

  label381 = gtk_label_new_with_mnemonic (_("<b><span color=\"Blue\"> Actualiser</span></b>"));
  gtk_widget_show (label381);
  gtk_box_pack_start (GTK_BOX (hbox50), label381, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label381, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label381), TRUE);

  label373 = gtk_label_new ("");
  gtk_widget_show (label373);
  gtk_fixed_put (GTK_FIXED (fixed15), label373, 400, 544);
  gtk_widget_set_size_request (label373, 400, 30);

  button56 = gtk_button_new ();
  gtk_widget_show (button56);
  gtk_fixed_put (GTK_FIXED (fixed15), button56, 32, 536);
  gtk_widget_set_size_request (button56, 352, 48);

  alignment78 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment78);
  gtk_container_add (GTK_CONTAINER (button56), alignment78);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment78), hbox78);

  image87 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image87);
  gtk_box_pack_start (GTK_BOX (hbox78), image87, FALSE, FALSE, 0);

  label383 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Le service le plus r\303\251clam\303\251</span></b>"));
  gtk_widget_show (label383);
  gtk_box_pack_start (GTK_BOX (hbox78), label383, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label383, -1, 29);
  gtk_label_set_use_markup (GTK_LABEL (label383), TRUE);

  label372 = gtk_label_new_with_mnemonic (_("<b><span color=\"Blue\"> Afficher</span></b>"));
  gtk_widget_show (label372);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label372);
  gtk_widget_set_size_request (label372, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label372), TRUE);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed12);
  gtk_widget_set_size_request (fixed12, 1074, 625);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed12), entry10, 368, 72);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed12), entry11, 368, 112);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed12), entry12, 368, 152);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed12), entry13, 360, 320);
  gtk_widget_set_size_request (entry13, 608, 96);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton2, 360, 224);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton3, 488, 224);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  spinbutton4_adj = gtk_adjustment_new (2020, 2021, 2050, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton4, 616, 224);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label279 = gtk_label_new ("");
  gtk_widget_show (label279);
  gtk_fixed_put (GTK_FIXED (fixed12), label279, 600, 280);
  gtk_widget_set_size_request (label279, 89, 25);

  button18 = gtk_button_new_with_mnemonic (_("Groupes : "));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed12), button18, 768, 16);
  gtk_widget_set_size_request (button18, 98, 29);

  checkbutton14_groupe = gtk_check_button_new_with_mnemonic (_("Groupe A "));
  gtk_widget_show (checkbutton14_groupe);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton14_groupe, 784, 56);
  gtk_widget_set_size_request (checkbutton14_groupe, 126, 24);

  checkbutton15_groupe = gtk_check_button_new_with_mnemonic (_("Groupe B "));
  gtk_widget_show (checkbutton15_groupe);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton15_groupe, 784, 88);
  gtk_widget_set_size_request (checkbutton15_groupe, 126, 24);

  label337 = gtk_label_new ("");
  gtk_widget_show (label337);
  gtk_fixed_put (GTK_FIXED (fixed12), label337, 0, 0);
  gtk_widget_set_size_request (label337, 0, 0);

  label338 = gtk_label_new ("");
  gtk_widget_show (label338);
  gtk_fixed_put (GTK_FIXED (fixed12), label338, 144, 392);
  gtk_widget_set_size_request (label338, 201, 33);

  radiobutton11_poste = gtk_radio_button_new_with_mnemonic (NULL, _("JOUR "));
  gtk_widget_show (radiobutton11_poste);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton11_poste, 792, 208);
  gtk_widget_set_size_request (radiobutton11_poste, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11_poste), radiobutton11_poste_group);
  radiobutton11_poste_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11_poste));

  radiobutton12_poste = gtk_radio_button_new_with_mnemonic (NULL, _("NUIT "));
  gtk_widget_show (radiobutton12_poste);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton12_poste, 792, 168);
  gtk_widget_set_size_request (radiobutton12_poste, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12_poste), radiobutton11_poste_group);
  radiobutton11_poste_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12_poste));

  button19 = gtk_button_new_with_mnemonic (_("Poste :"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed12), button19, 768, 120);
  gtk_widget_set_size_request (button19, 96, 29);

  button5_ok_ = gtk_button_new ();
  gtk_widget_show (button5_ok_);
  gtk_fixed_put (GTK_FIXED (fixed12), button5_ok_, 768, 248);
  gtk_widget_set_size_request (button5_ok_, 106, 29);

  alignment59 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment59);
  gtk_container_add (GTK_CONTAINER (button5_ok_), alignment59);

  hbox59 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox59);
  gtk_container_add (GTK_CONTAINER (alignment59), hbox59);

  image62 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox59), image62, FALSE, FALSE, 0);

  label377 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> ok</span></b>"));
  gtk_widget_show (label377);
  gtk_box_pack_start (GTK_BOX (hbox59), label377, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label377, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label377), TRUE);

  label356 = gtk_label_new ("");
  gtk_widget_show (label356);
  gtk_fixed_put (GTK_FIXED (fixed12), label356, 688, 0);
  gtk_widget_set_size_request (label356, 289, 41);

  label390 = gtk_label_new ("");
  gtk_widget_show (label390);
  gtk_fixed_put (GTK_FIXED (fixed12), label390, 688, 0);
  gtk_widget_set_size_request (label390, 289, 41);

  label391 = gtk_label_new ("");
  gtk_widget_show (label391);
  gtk_fixed_put (GTK_FIXED (fixed12), label391, 872, 216);
  gtk_widget_set_size_request (label391, 265, 128);

  label360 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\">Pr\303\251nom</span></b>"));
  gtk_widget_show (label360);
  gtk_fixed_put (GTK_FIXED (fixed12), label360, 280, 112);
  gtk_widget_set_size_request (label360, 98, 29);
  gtk_label_set_use_markup (GTK_LABEL (label360), TRUE);

  label334 = gtk_label_new ("");
  gtk_widget_show (label334);
  gtk_fixed_put (GTK_FIXED (fixed12), label334, 544, 112);
  gtk_widget_set_size_request (label334, 192, 25);

  label359 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Nom</span></b>"));
  gtk_widget_show (label359);
  gtk_fixed_put (GTK_FIXED (fixed12), label359, 296, 72);
  gtk_widget_set_size_request (label359, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label359), TRUE);

  label333 = gtk_label_new ("");
  gtk_widget_show (label333);
  gtk_fixed_put (GTK_FIXED (fixed12), label333, 528, 72);
  gtk_widget_set_size_request (label333, 145, 33);

  label335 = gtk_label_new ("");
  gtk_widget_show (label335);
  gtk_fixed_put (GTK_FIXED (fixed12), label335, 480, 264);
  gtk_widget_set_size_request (label335, 145, 33);

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed12), combobox6, 360, 264);
  gtk_widget_set_size_request (combobox6, 113, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Restauration"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Hebergement"));

  label361 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Service</span></b>"));
  gtk_widget_show (label361);
  gtk_fixed_put (GTK_FIXED (fixed12), label361, 272, 272);
  gtk_widget_set_size_request (label361, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label361), TRUE);

  label357 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Date de Reclamation </span></b>"));
  gtk_widget_show (label357);
  gtk_fixed_put (GTK_FIXED (fixed12), label357, 256, 200);
  gtk_widget_set_size_request (label357, 175, 29);
  gtk_label_set_use_markup (GTK_LABEL (label357), TRUE);

  label336 = gtk_label_new ("");
  gtk_widget_show (label336);
  gtk_fixed_put (GTK_FIXED (fixed12), label336, 544, 152);
  gtk_widget_set_size_request (label336, 145, 33);

  label362 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Cin :</span></b>"));
  gtk_widget_show (label362);
  gtk_fixed_put (GTK_FIXED (fixed12), label362, 296, 152);
  gtk_widget_set_size_request (label362, 74, 29);
  gtk_label_set_use_markup (GTK_LABEL (label362), TRUE);

  label366 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Sujet</span></b>"));
  gtk_widget_show (label366);
  gtk_fixed_put (GTK_FIXED (fixed12), label366, 256, 320);
  gtk_widget_set_size_request (label366, 130, 29);
  gtk_label_set_use_markup (GTK_LABEL (label366), TRUE);

  ajou_ch = gtk_button_new ();
  gtk_widget_show (ajou_ch);
  gtk_fixed_put (GTK_FIXED (fixed12), ajou_ch, 840, 432);
  gtk_widget_set_size_request (ajou_ch, 130, 45);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (ajou_ch), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label376 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Ajouter</span></b>"));
  gtk_widget_show (label376);
  gtk_box_pack_start (GTK_BOX (hbox12), label376, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label376, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label376), TRUE);

  label393 = gtk_label_new_with_mnemonic (_("<b><span color=\"Blue\">  Formulaire reclamation : </span></b>"));
  gtk_widget_show (label393);
  gtk_fixed_put (GTK_FIXED (fixed12), label393, 224, 16);
  gtk_widget_set_size_request (label393, 240, 32);
  gtk_label_set_use_markup (GTK_LABEL (label393), TRUE);

  label363 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Jour</span></b>"));
  gtk_widget_show (label363);
  gtk_fixed_put (GTK_FIXED (fixed12), label363, 288, 224);
  gtk_widget_set_size_request (label363, 74, 29);
  gtk_label_set_use_markup (GTK_LABEL (label363), TRUE);

  label364 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Mois</span></b>"));
  gtk_widget_show (label364);
  gtk_fixed_put (GTK_FIXED (fixed12), label364, 416, 224);
  gtk_widget_set_size_request (label364, 74, 29);
  gtk_label_set_use_markup (GTK_LABEL (label364), TRUE);

  label365 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Ann\303\251e</span></b>"));
  gtk_widget_show (label365);
  gtk_fixed_put (GTK_FIXED (fixed12), label365, 544, 224);
  gtk_widget_set_size_request (label365, 74, 29);
  gtk_label_set_use_markup (GTK_LABEL (label365), TRUE);

  label369 = gtk_label_new_with_mnemonic (_("<b><span color=\"Blue\"> Espace Ajout</span></b>"));
  gtk_widget_show (label369);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label369);
  gtk_widget_set_size_request (label369, -1, 29);
  gtk_label_set_use_markup (GTK_LABEL (label369), TRUE);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed14);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed14), entry16, 304, 56);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed14), entry17, 328, 120);
  gtk_widget_set_size_request (entry17, 181, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed14), entry18, 328, 160);
  gtk_widget_set_size_request (entry18, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed14), entry19, 328, 208);
  gtk_widget_set_size_request (entry19, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed14), entry20, 320, 328);
  gtk_widget_set_size_request (entry20, 208, 80);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  label84 = gtk_label_new ("");
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed14), label84, 360, 96);
  gtk_widget_set_size_request (label84, 113, 25);

  label317 = gtk_label_new ("");
  gtk_widget_show (label317);
  gtk_fixed_put (GTK_FIXED (fixed14), label317, 472, 24);
  gtk_widget_set_size_request (label317, 208, 33);

  rech_ch = gtk_button_new ();
  gtk_widget_show (rech_ch);
  gtk_fixed_put (GTK_FIXED (fixed14), rech_ch, 472, 48);
  gtk_widget_set_size_request (rech_ch, 112, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (rech_ch), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label379 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Rechercher</span></b>"));
  gtk_widget_show (label379);
  gtk_box_pack_start (GTK_BOX (hbox15), label379, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label379, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label379), TRUE);

  label394 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">  ID \303\240 Rechercher : </span></b>"));
  gtk_widget_show (label394);
  gtk_fixed_put (GTK_FIXED (fixed14), label394, 104, 48);
  gtk_widget_set_size_request (label394, 192, 48);
  gtk_label_set_use_markup (GTK_LABEL (label394), TRUE);

  label384 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\">Pr\303\251nom</span></b>"));
  gtk_widget_show (label384);
  gtk_fixed_put (GTK_FIXED (fixed14), label384, 232, 160);
  gtk_widget_set_size_request (label384, 98, 37);
  gtk_label_set_use_markup (GTK_LABEL (label384), TRUE);

  label387 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\">CIN</span></b>"));
  gtk_widget_show (label387);
  gtk_fixed_put (GTK_FIXED (fixed14), label387, 232, 208);
  gtk_widget_set_size_request (label387, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (label387), TRUE);

  label386 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\">Service</span></b>"));
  gtk_widget_show (label386);
  gtk_fixed_put (GTK_FIXED (fixed14), label386, 232, 272);
  gtk_widget_set_size_request (label386, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label386), TRUE);

  label389 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\">Sujet</span></b>"));
  gtk_widget_show (label389);
  gtk_fixed_put (GTK_FIXED (fixed14), label389, 184, 320);
  gtk_widget_set_size_request (label389, 192, 40);
  gtk_label_set_use_markup (GTK_LABEL (label389), TRUE);

  label358 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"> Date de Reclamation </span></b>"));
  gtk_widget_show (label358);
  gtk_fixed_put (GTK_FIXED (fixed14), label358, 152, 432);
  gtk_widget_set_size_request (label358, 162, 29);
  gtk_label_set_use_markup (GTK_LABEL (label358), TRUE);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed14), combobox7, 328, 272);
  gtk_widget_set_size_request (combobox7, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Restauration"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Hebergement"));

  label385 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\">Nom</span></b>"));
  gtk_widget_show (label385);
  gtk_fixed_put (GTK_FIXED (fixed14), label385, 240, 120);
  gtk_widget_set_size_request (label385, 98, 37);
  gtk_label_set_use_markup (GTK_LABEL (label385), TRUE);

  label354 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\"></span></b>"));
  gtk_widget_show (label354);
  gtk_fixed_put (GTK_FIXED (fixed14), label354, 584, 48);
  gtk_widget_set_size_request (label354, 241, 33);
  gtk_label_set_use_markup (GTK_LABEL (label354), TRUE);

  modi_ch = gtk_button_new ();
  gtk_widget_show (modi_ch);
  gtk_fixed_put (GTK_FIXED (fixed14), modi_ch, 488, 656);
  gtk_widget_set_size_request (modi_ch, 122, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (modi_ch), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label380 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Modifier</span></b>"));
  gtk_widget_show (label380);
  gtk_box_pack_start (GTK_BOX (hbox19), label380, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label380, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label380), TRUE);

  calendar = gtk_calendar_new ();
  gtk_widget_show (calendar);
  gtk_fixed_put (GTK_FIXED (fixed14), calendar, 344, 456);
  gtk_widget_set_size_request (calendar, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label371 = gtk_label_new_with_mnemonic (_("<b><span color=\"Blue\"> Rechercher et modification</span></b>"));
  gtk_widget_show (label371);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label371);
  gtk_widget_set_size_request (label371, -1, 29);
  gtk_label_set_use_markup (GTK_LABEL (label371), TRUE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed13);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed13), entry15, 408, 88);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  label83 = gtk_label_new ("");
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed13), label83, 376, 264);
  gtk_widget_set_size_request (label83, 281, 41);

  label332 = gtk_label_new (_("<b><span color=\"red\"> </span></b>"));
  gtk_widget_show (label332);
  gtk_fixed_put (GTK_FIXED (fixed13), label332, 368, 184);
  gtk_widget_set_size_request (label332, 289, 49);
  gtk_label_set_use_markup (GTK_LABEL (label332), TRUE);

  supp_ch = gtk_button_new ();
  gtk_widget_show (supp_ch);
  gtk_fixed_put (GTK_FIXED (fixed13), supp_ch, 600, 80);
  gtk_widget_set_size_request (supp_ch, 122, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (supp_ch), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label378 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Supprimer</span></b>"));
  gtk_widget_show (label378);
  gtk_box_pack_start (GTK_BOX (hbox13), label378, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label378, 82, 29);
  gtk_label_set_use_markup (GTK_LABEL (label378), TRUE);

  label392 = gtk_label_new_with_mnemonic (_("<b><span color=\"Red\"> ID \303\240 Supprimer</span></b>"));
  gtk_widget_show (label392);
  gtk_fixed_put (GTK_FIXED (fixed13), label392, 248, 56);
  gtk_widget_set_size_request (label392, 176, 80);
  gtk_label_set_use_markup (GTK_LABEL (label392), TRUE);

  label370 = gtk_label_new_with_mnemonic (_("<b><span color=\"Blue\"> Espace Supprimer</span></b>"));
  gtk_widget_show (label370);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 3), label370);
  gtk_widget_set_size_request (label370, -1, 29);
  gtk_label_set_use_markup (GTK_LABEL (label370), TRUE);

  g_signal_connect ((gpointer) button7_quiter_ouv, "clicked",
                    G_CALLBACK (on_button7_quiter_ouv_clicked),
                    NULL);
  g_signal_connect ((gpointer) instagram, "clicked",
                    G_CALLBACK (on_instagram_clicked),
                    NULL);
  g_signal_connect ((gpointer) facebook, "clicked",
                    G_CALLBACK (on_facebook_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview5, "row_activated",
                    G_CALLBACK (on_treeview5_row_activated),
                    NULL);
  g_signal_connect ((gpointer) supp_tree_ch, "clicked",
                    G_CALLBACK (on_supp_tree_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_ch, "clicked",
                    G_CALLBACK (on_actua_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) button56, "clicked",
                    G_CALLBACK (on_button56_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton14_groupe, "toggled",
                    G_CALLBACK (on_checkbutton14_groupe_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton15_groupe, "toggled",
                    G_CALLBACK (on_checkbutton15_groupe_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton11_poste, "toggled",
                    G_CALLBACK (on_radiobutton11_poste_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton12_poste, "toggled",
                    G_CALLBACK (on_radiobutton12_poste_toggled),
                    NULL);
  g_signal_connect ((gpointer) button5_ok_, "clicked",
                    G_CALLBACK (on_button5_ok__clicked),
                    NULL);
  g_signal_connect ((gpointer) ajou_ch, "clicked",
                    G_CALLBACK (on_ajou_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) rech_ch, "clicked",
                    G_CALLBACK (on_rech_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) modi_ch, "clicked",
                    G_CALLBACK (on_modi_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) supp_ch, "clicked",
                    G_CALLBACK (on_supp_ch_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label360), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label359), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label361), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label362), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label366), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label393), button18);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label363), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label364), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label365), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label394), rech_ch);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label384), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label387), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label386), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label389), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label385), entry10);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label354), entry10);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_reclam, Gestion_reclam, "Gestion_reclam");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image89, "image89");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, button7_quiter_ouv, "button7_quiter_ouv");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment74, "alignment74");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox74, "hbox74");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image79, "image79");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label315, "label315");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, instagram, "instagram");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image86, "image86");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, facebook, "facebook");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image85, "image85");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label238, "label238");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, supp_tree_ch, "supp_tree_ch");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment51, "alignment51");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image54, "image54");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label382, "label382");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, modifier_ch, "modifier_ch");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment50, "alignment50");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image53, "image53");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label381, "label381");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label373, "label373");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, button56, "button56");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment78, "alignment78");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image87, "image87");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label383, "label383");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label372, "label372");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label279, "label279");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, button18, "button18");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, checkbutton14_groupe, "checkbutton14_groupe");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, checkbutton15_groupe, "checkbutton15_groupe");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label337, "label337");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label338, "label338");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, radiobutton11_poste, "radiobutton11_poste");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, radiobutton12_poste, "radiobutton12_poste");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, button19, "button19");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, button5_ok_, "button5_ok_");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image62, "image62");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label377, "label377");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label356, "label356");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label390, "label390");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label391, "label391");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label360, "label360");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label334, "label334");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label359, "label359");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label333, "label333");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label335, "label335");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label361, "label361");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label357, "label357");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label336, "label336");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label362, "label362");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label366, "label366");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, ajou_ch, "ajou_ch");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image12, "image12");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label376, "label376");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label393, "label393");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label363, "label363");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label364, "label364");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label365, "label365");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label369, "label369");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label84, "label84");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label317, "label317");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, rech_ch, "rech_ch");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image15, "image15");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label379, "label379");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label394, "label394");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label384, "label384");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label387, "label387");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label386, "label386");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label389, "label389");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label358, "label358");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label385, "label385");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label354, "label354");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, modi_ch, "modi_ch");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image19, "image19");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label380, "label380");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, calendar, "calendar");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label371, "label371");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label83, "label83");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label332, "label332");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, supp_ch, "supp_ch");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, image13, "image13");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label378, "label378");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label392, "label392");
  GLADE_HOOKUP_OBJECT (Gestion_reclam, label370, "label370");

  return Gestion_reclam;
}

