/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Admin (void);
GtkWidget* create_auth (void);
GtkWidget* create_inscription (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window6 (void);
GtkWidget* create_etudiant (void);
GtkWidget* create_ajouterEtudiant (void);
GtkWidget* create_recherchee (void);
