/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Admin (void)
{
  GtkWidget *Admin;
  GtkWidget *fixed3;
  GtkWidget *treeviewAffiListUser;
  GtkWidget *quit_ad;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label101;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *label323;
  GtkWidget *label321;
  GtkWidget *label320;
  GtkWidget *label319;
  GtkWidget *label318;
  GtkWidget *label324;
  GtkWidget *label322;
  GtkWidget *entry6;
  GtkWidget *combobox34;
  GtkWidget *buttonAffiUser;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image111;
  GtkWidget *label316;
  GtkWidget *buttonSupprimer;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image110;
  GtkWidget *label315;
  GtkWidget *buttonModifier;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image112;
  GtkWidget *label317;
  GtkWidget *button7_chercheryosra;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image115;
  GtkWidget *label335;
  GtkWidget *buttonRestau;
  GtkWidget *buttonValider;

  Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Admin), _("Espace Administrateur "));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Admin), fixed3);

  treeviewAffiListUser = gtk_tree_view_new ();
  gtk_widget_show (treeviewAffiListUser);
  gtk_fixed_put (GTK_FIXED (fixed3), treeviewAffiListUser, 40, 40);
  gtk_widget_set_size_request (treeviewAffiListUser, 408, 384);

  quit_ad = gtk_button_new ();
  gtk_widget_show (quit_ad);
  gtk_fixed_put (GTK_FIXED (fixed3), quit_ad, 968, 0);
  gtk_widget_set_size_request (quit_ad, 88, 48);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (quit_ad), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox22), label101, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 816, 88);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 816, 152);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 816, 224);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 816, 288);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 816, 472);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label323 = gtk_label_new (_("Num telephone"));
  gtk_widget_show (label323);
  gtk_fixed_put (GTK_FIXED (fixed3), label323, 680, 424);
  gtk_widget_set_size_request (label323, 128, 24);

  label321 = gtk_label_new (_("Password"));
  gtk_widget_show (label321);
  gtk_fixed_put (GTK_FIXED (fixed3), label321, 664, 288);
  gtk_widget_set_size_request (label321, 112, 32);

  label320 = gtk_label_new (_("Username"));
  gtk_widget_show (label320);
  gtk_fixed_put (GTK_FIXED (fixed3), label320, 672, 224);
  gtk_widget_set_size_request (label320, 96, 32);

  label319 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label319);
  gtk_fixed_put (GTK_FIXED (fixed3), label319, 672, 152);
  gtk_widget_set_size_request (label319, 88, 32);

  label318 = gtk_label_new (_("Nom"));
  gtk_widget_show (label318);
  gtk_fixed_put (GTK_FIXED (fixed3), label318, 648, 80);
  gtk_widget_set_size_request (label318, 112, 32);

  label324 = gtk_label_new (_("CIN"));
  gtk_widget_show (label324);
  gtk_fixed_put (GTK_FIXED (fixed3), label324, 680, 472);
  gtk_widget_set_size_request (label324, 57, 17);

  label322 = gtk_label_new (_("Role"));
  gtk_widget_show (label322);
  gtk_fixed_put (GTK_FIXED (fixed3), label322, 688, 368);
  gtk_widget_set_size_request (label322, 57, 17);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 816, 424);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  combobox34 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox34);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox34, 816, 360);
  gtk_widget_set_size_request (combobox34, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox34), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox34), _("Technicien1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox34), _("Technicien2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox34), _("Technicien3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox34), _("Technicien4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox34), _("Technicien5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox34), "");

  buttonAffiUser = gtk_button_new ();
  gtk_widget_show (buttonAffiUser);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAffiUser, 40, 472);
  gtk_widget_set_size_request (buttonAffiUser, 104, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (buttonAffiUser), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image111 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image111);
  gtk_box_pack_start (GTK_BOX (hbox24), image111, FALSE, FALSE, 0);

  label316 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label316);
  gtk_box_pack_start (GTK_BOX (hbox24), label316, FALSE, FALSE, 0);

  buttonSupprimer = gtk_button_new ();
  gtk_widget_show (buttonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonSupprimer, 144, 472);
  gtk_widget_set_size_request (buttonSupprimer, 104, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (buttonSupprimer), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image110 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image110);
  gtk_box_pack_start (GTK_BOX (hbox23), image110, FALSE, FALSE, 0);

  label315 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label315);
  gtk_box_pack_start (GTK_BOX (hbox23), label315, FALSE, FALSE, 0);

  buttonModifier = gtk_button_new ();
  gtk_widget_show (buttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonModifier, 248, 472);
  gtk_widget_set_size_request (buttonModifier, 96, 37);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (buttonModifier), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image112 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image112);
  gtk_box_pack_start (GTK_BOX (hbox25), image112, FALSE, FALSE, 0);

  label317 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label317);
  gtk_box_pack_start (GTK_BOX (hbox25), label317, FALSE, FALSE, 0);

  button7_chercheryosra = gtk_button_new ();
  gtk_widget_show (button7_chercheryosra);
  gtk_fixed_put (GTK_FIXED (fixed3), button7_chercheryosra, 352, 472);
  gtk_widget_set_size_request (button7_chercheryosra, 104, 32);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button7_chercheryosra), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image115 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image115);
  gtk_box_pack_start (GTK_BOX (hbox28), image115, FALSE, FALSE, 0);

  label335 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label335);
  gtk_box_pack_start (GTK_BOX (hbox28), label335, FALSE, FALSE, 0);

  buttonRestau = gtk_button_new_with_mnemonic (_("Espace Etudiant"));
  gtk_widget_show (buttonRestau);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonRestau, 768, 24);
  gtk_widget_set_size_request (buttonRestau, 152, 32);

  buttonValider = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (buttonValider);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonValider, 936, 504);
  gtk_widget_set_size_request (buttonValider, 96, 40);

  g_signal_connect ((gpointer) treeviewAffiListUser, "row_activated",
                    G_CALLBACK (on_treeviewAffiListUser_row_activated),
                    NULL);
  g_signal_connect ((gpointer) quit_ad, "clicked",
                    G_CALLBACK (on_quit_ad_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAffiUser, "clicked",
                    G_CALLBACK (on_buttonAffiUser_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimer, "clicked",
                    G_CALLBACK (on_buttonSupprimeryo_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier, "clicked",
                    G_CALLBACK (on_buttonModifieryo_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7_chercheryosra, "clicked",
                    G_CALLBACK (on_button7_chercheryosra_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRestau, "clicked",
                    G_CALLBACK (on_buttonRestau_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonValider, "clicked",
                    G_CALLBACK (on_buttonValideryo_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Admin, Admin, "Admin");
  GLADE_HOOKUP_OBJECT (Admin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Admin, treeviewAffiListUser, "treeviewAffiListUser");
  GLADE_HOOKUP_OBJECT (Admin, quit_ad, "quit_ad");
  GLADE_HOOKUP_OBJECT (Admin, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Admin, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Admin, image22, "image22");
  GLADE_HOOKUP_OBJECT (Admin, label101, "label101");
  GLADE_HOOKUP_OBJECT (Admin, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Admin, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Admin, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Admin, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Admin, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Admin, label323, "label323");
  GLADE_HOOKUP_OBJECT (Admin, label321, "label321");
  GLADE_HOOKUP_OBJECT (Admin, label320, "label320");
  GLADE_HOOKUP_OBJECT (Admin, label319, "label319");
  GLADE_HOOKUP_OBJECT (Admin, label318, "label318");
  GLADE_HOOKUP_OBJECT (Admin, label324, "label324");
  GLADE_HOOKUP_OBJECT (Admin, label322, "label322");
  GLADE_HOOKUP_OBJECT (Admin, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Admin, combobox34, "combobox34");
  GLADE_HOOKUP_OBJECT (Admin, buttonAffiUser, "buttonAffiUser");
  GLADE_HOOKUP_OBJECT (Admin, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (Admin, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (Admin, image111, "image111");
  GLADE_HOOKUP_OBJECT (Admin, label316, "label316");
  GLADE_HOOKUP_OBJECT (Admin, buttonSupprimer, "buttonSupprimer");
  GLADE_HOOKUP_OBJECT (Admin, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Admin, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Admin, image110, "image110");
  GLADE_HOOKUP_OBJECT (Admin, label315, "label315");
  GLADE_HOOKUP_OBJECT (Admin, buttonModifier, "buttonModifier");
  GLADE_HOOKUP_OBJECT (Admin, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (Admin, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (Admin, image112, "image112");
  GLADE_HOOKUP_OBJECT (Admin, label317, "label317");
  GLADE_HOOKUP_OBJECT (Admin, button7_chercheryosra, "button7_chercheryosra");
  GLADE_HOOKUP_OBJECT (Admin, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (Admin, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (Admin, image115, "image115");
  GLADE_HOOKUP_OBJECT (Admin, label335, "label335");
  GLADE_HOOKUP_OBJECT (Admin, buttonRestau, "buttonRestau");
  GLADE_HOOKUP_OBJECT (Admin, buttonValider, "buttonValider");

  return Admin;
}

GtkWidget*
create_auth (void)
{
  GtkWidget *auth;
  GtkWidget *eventbox1;
  GtkWidget *fixed2;
  GtkWidget *us;
  GtkWidget *Pw;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *log;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *login;
  GtkWidget *auth_youtube;
  GtkWidget *image50;
  GtkWidget *auth_facebook;
  GtkWidget *image51;
  GtkWidget *auth_instagram;
  GtkWidget *image52;
  GtkWidget *label314;
  GtkWidget *image67;
  GtkWidget *ajout;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;

  auth = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (auth), _("authentification"));

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (auth), eventbox1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed2);

  us = gtk_entry_new ();
  gtk_widget_show (us);
  gtk_fixed_put (GTK_FIXED (fixed2), us, 136, 176);
  gtk_widget_set_size_request (us, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (us), 8226);

  Pw = gtk_entry_new ();
  gtk_widget_show (Pw);
  gtk_fixed_put (GTK_FIXED (fixed2), Pw, 136, 232);
  gtk_widget_set_size_request (Pw, 176, 32);
  gtk_entry_set_visibility (GTK_ENTRY (Pw), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (Pw), 8226);

  button5 = gtk_button_new_with_mnemonic (_("user Name :"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 24, 176);
  gtk_widget_set_size_request (button5, 98, 29);

  button6 = gtk_button_new_with_mnemonic (_("Password :"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 24, 232);
  gtk_widget_set_size_request (button6, 98, 37);

  log = gtk_button_new ();
  gtk_widget_show (log);
  gtk_fixed_put (GTK_FIXED (fixed2), log, 360, 184);
  gtk_widget_set_size_request (log, 80, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (log), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  login = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (login);
  gtk_box_pack_start (GTK_BOX (hbox1), login, FALSE, FALSE, 0);

  auth_youtube = gtk_button_new ();
  gtk_widget_show (auth_youtube);
  gtk_fixed_put (GTK_FIXED (fixed2), auth_youtube, 464, 16);
  gtk_widget_set_size_request (auth_youtube, 48, 40);

  image50 = create_pixmap (auth, "youtube.png");
  gtk_widget_show (image50);
  gtk_container_add (GTK_CONTAINER (auth_youtube), image50);

  auth_facebook = gtk_button_new ();
  gtk_widget_show (auth_facebook);
  gtk_fixed_put (GTK_FIXED (fixed2), auth_facebook, 520, 16);
  gtk_widget_set_size_request (auth_facebook, 48, 40);

  image51 = create_pixmap (auth, "button-facebookfinal.svg");
  gtk_widget_show (image51);
  gtk_container_add (GTK_CONTAINER (auth_facebook), image51);

  auth_instagram = gtk_button_new ();
  gtk_widget_show (auth_instagram);
  gtk_fixed_put (GTK_FIXED (fixed2), auth_instagram, 576, 16);
  gtk_widget_set_size_request (auth_instagram, 48, 40);

  image52 = create_pixmap (auth, "aaaaaaaaaaa.png");
  gtk_widget_show (image52);
  gtk_container_add (GTK_CONTAINER (auth_instagram), image52);

  label314 = gtk_label_new ("");
  gtk_widget_show (label314);
  gtk_fixed_put (GTK_FIXED (fixed2), label314, 448, 184);
  gtk_widget_set_size_request (label314, 201, 41);

  image67 = create_pixmap (auth, "logos.png");
  gtk_widget_show (image67);
  gtk_fixed_put (GTK_FIXED (fixed2), image67, 32, 0);
  gtk_widget_set_size_request (image67, 368, 240);

  ajout = gtk_button_new ();
  gtk_widget_show (ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), ajout, 240, 288);
  gtk_widget_set_size_request (ajout, 176, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ajout), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("ajouter un compte "));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) log, "clicked",
                    G_CALLBACK (on_button2_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) auth_youtube, "clicked",
                    G_CALLBACK (on_auth_youtube_clicked),
                    NULL);
  g_signal_connect ((gpointer) auth_facebook, "clicked",
                    G_CALLBACK (on_auth_facebook_clicked),
                    NULL);
  g_signal_connect ((gpointer) auth_instagram, "clicked",
                    G_CALLBACK (on_auth_instagram_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout, "clicked",
                    G_CALLBACK (on_ajoutyo_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (auth, auth, "auth");
  GLADE_HOOKUP_OBJECT (auth, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (auth, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (auth, us, "us");
  GLADE_HOOKUP_OBJECT (auth, Pw, "Pw");
  GLADE_HOOKUP_OBJECT (auth, button5, "button5");
  GLADE_HOOKUP_OBJECT (auth, button6, "button6");
  GLADE_HOOKUP_OBJECT (auth, log, "log");
  GLADE_HOOKUP_OBJECT (auth, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (auth, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (auth, image1, "image1");
  GLADE_HOOKUP_OBJECT (auth, login, "login");
  GLADE_HOOKUP_OBJECT (auth, auth_youtube, "auth_youtube");
  GLADE_HOOKUP_OBJECT (auth, image50, "image50");
  GLADE_HOOKUP_OBJECT (auth, auth_facebook, "auth_facebook");
  GLADE_HOOKUP_OBJECT (auth, image51, "image51");
  GLADE_HOOKUP_OBJECT (auth, auth_instagram, "auth_instagram");
  GLADE_HOOKUP_OBJECT (auth, image52, "image52");
  GLADE_HOOKUP_OBJECT (auth, label314, "label314");
  GLADE_HOOKUP_OBJECT (auth, image67, "image67");
  GLADE_HOOKUP_OBJECT (auth, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (auth, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (auth, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (auth, image3, "image3");
  GLADE_HOOKUP_OBJECT (auth, label6, "label6");

  return auth;
}

GtkWidget*
create_inscription (void)
{
  GtkWidget *inscription;
  GtkWidget *fixed1;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *user;
  GtkWidget *Pass;
  GtkWidget *label2_nom;
  GtkWidget *label3_prenom;
  GtkWidget *label4_user;
  GtkWidget *num;
  GtkWidget *cin;
  GtkWidget *label5;
  GtkWidget *label6_role;
  GtkWidget *label5_Pw;
  GtkWidget *label1;
  GtkWidget *label261;
  GtkWidget *label255;
  GtkWidget *label256;
  GtkWidget *label257;
  GtkWidget *label258;
  GtkWidget *label259;
  GtkWidget *label260;
  GtkWidget *label4;
  GtkWidget *combobox33;
  GtkWidget *button1_ajout;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;

  inscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscription), _("inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (inscription), fixed1);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 152, 104);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), prenom, 152, 168);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  user = gtk_entry_new ();
  gtk_widget_show (user);
  gtk_fixed_put (GTK_FIXED (fixed1), user, 152, 232);
  gtk_widget_set_size_request (user, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (user), 8226);

  Pass = gtk_entry_new ();
  gtk_widget_show (Pass);
  gtk_fixed_put (GTK_FIXED (fixed1), Pass, 152, 288);
  gtk_widget_set_size_request (Pass, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (Pass), 8226);

  label2_nom = gtk_label_new (_("Nom :"));
  gtk_widget_show (label2_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), label2_nom, 32, 104);
  gtk_widget_set_size_request (label2_nom, 80, 32);

  label3_prenom = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label3_prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), label3_prenom, 24, 168);
  gtk_widget_set_size_request (label3_prenom, 80, 24);

  label4_user = gtk_label_new (_("Username :"));
  gtk_widget_show (label4_user);
  gtk_fixed_put (GTK_FIXED (fixed1), label4_user, 24, 232);
  gtk_widget_set_size_request (label4_user, 73, 24);

  num = gtk_entry_new ();
  gtk_widget_show (num);
  gtk_fixed_put (GTK_FIXED (fixed1), num, 160, 400);
  gtk_widget_set_size_request (num, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (num), 8226);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed1), cin, 160, 456);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  label5 = gtk_label_new (_("Num CIN"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 32, 456);
  gtk_widget_set_size_request (label5, 88, 25);

  label6_role = gtk_label_new (_("Role  :"));
  gtk_widget_show (label6_role);
  gtk_fixed_put (GTK_FIXED (fixed1), label6_role, 32, 352);
  gtk_widget_set_size_request (label6_role, 81, 24);

  label5_Pw = gtk_label_new (_("Password  :"));
  gtk_widget_show (label5_Pw);
  gtk_fixed_put (GTK_FIXED (fixed1), label5_Pw, 24, 288);
  gtk_widget_set_size_request (label5_Pw, 81, 24);

  label1 = gtk_label_new (_("Inscription :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 272, 32);
  gtk_widget_set_size_request (label1, 128, 32);

  label261 = gtk_label_new ("");
  gtk_widget_show (label261);
  gtk_fixed_put (GTK_FIXED (fixed1), label261, 64, 32);
  gtk_widget_set_size_request (label261, 200, 33);

  label255 = gtk_label_new ("");
  gtk_widget_show (label255);
  gtk_fixed_put (GTK_FIXED (fixed1), label255, 368, 104);
  gtk_widget_set_size_request (label255, 152, 32);

  label256 = gtk_label_new ("");
  gtk_widget_show (label256);
  gtk_fixed_put (GTK_FIXED (fixed1), label256, 376, 168);
  gtk_widget_set_size_request (label256, 144, 32);

  label257 = gtk_label_new ("");
  gtk_widget_show (label257);
  gtk_fixed_put (GTK_FIXED (fixed1), label257, 376, 232);
  gtk_widget_set_size_request (label257, 136, 32);

  label258 = gtk_label_new ("");
  gtk_widget_show (label258);
  gtk_fixed_put (GTK_FIXED (fixed1), label258, 376, 296);
  gtk_widget_set_size_request (label258, 136, 32);

  label259 = gtk_label_new ("");
  gtk_widget_show (label259);
  gtk_fixed_put (GTK_FIXED (fixed1), label259, 376, 400);
  gtk_widget_set_size_request (label259, 136, 32);

  label260 = gtk_label_new ("");
  gtk_widget_show (label260);
  gtk_fixed_put (GTK_FIXED (fixed1), label260, 368, 456);
  gtk_widget_set_size_request (label260, 144, 32);

  label4 = gtk_label_new (_("Num telephone"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 16, 400);
  gtk_widget_set_size_request (label4, 128, 24);

  combobox33 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox33);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox33, 184, 344);
  gtk_widget_set_size_request (combobox33, 88, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox33), _("Admin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox33), _("Technicien1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox33), _("Technicien2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox33), _("Technicien3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox33), _("Technicien4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox33), _("Technicien5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox33), "");

  button1_ajout = gtk_button_new ();
  gtk_widget_show (button1_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_ajout, 528, 280);
  gtk_widget_set_size_request (button1_ajout, 80, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1_ajout), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Valid\303\251e"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1_ajout, "clicked",
                    G_CALLBACK (on_button1_ajoutyo_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscription, inscription, "inscription");
  GLADE_HOOKUP_OBJECT (inscription, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (inscription, nom, "nom");
  GLADE_HOOKUP_OBJECT (inscription, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (inscription, user, "user");
  GLADE_HOOKUP_OBJECT (inscription, Pass, "Pass");
  GLADE_HOOKUP_OBJECT (inscription, label2_nom, "label2_nom");
  GLADE_HOOKUP_OBJECT (inscription, label3_prenom, "label3_prenom");
  GLADE_HOOKUP_OBJECT (inscription, label4_user, "label4_user");
  GLADE_HOOKUP_OBJECT (inscription, num, "num");
  GLADE_HOOKUP_OBJECT (inscription, cin, "cin");
  GLADE_HOOKUP_OBJECT (inscription, label5, "label5");
  GLADE_HOOKUP_OBJECT (inscription, label6_role, "label6_role");
  GLADE_HOOKUP_OBJECT (inscription, label5_Pw, "label5_Pw");
  GLADE_HOOKUP_OBJECT (inscription, label1, "label1");
  GLADE_HOOKUP_OBJECT (inscription, label261, "label261");
  GLADE_HOOKUP_OBJECT (inscription, label255, "label255");
  GLADE_HOOKUP_OBJECT (inscription, label256, "label256");
  GLADE_HOOKUP_OBJECT (inscription, label257, "label257");
  GLADE_HOOKUP_OBJECT (inscription, label258, "label258");
  GLADE_HOOKUP_OBJECT (inscription, label259, "label259");
  GLADE_HOOKUP_OBJECT (inscription, label260, "label260");
  GLADE_HOOKUP_OBJECT (inscription, label4, "label4");
  GLADE_HOOKUP_OBJECT (inscription, combobox33, "combobox33");
  GLADE_HOOKUP_OBJECT (inscription, button1_ajout, "button1_ajout");
  GLADE_HOOKUP_OBJECT (inscription, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (inscription, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (inscription, image2, "image2");
  GLADE_HOOKUP_OBJECT (inscription, label3, "label3");

  return inscription;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");

  return window6;
}

GtkWidget*
create_etudiant (void)
{
  GtkWidget *etudiant;
  GtkWidget *fixed4;
  GtkWidget *treeview1;
  GtkWidget *entry7;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label327;
  GtkWidget *label325;
  GtkWidget *button_calculEtudiant;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image113;
  GtkWidget *label326;
  GtkWidget *buttonEspaceAjouter;
  GtkWidget *buttonActualiser;

  etudiant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (etudiant), _("Etudiant"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (etudiant), fixed4);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 296, 64);
  gtk_widget_set_size_request (treeview1, 336, 224);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 32, 184);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 96, 272);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label327 = gtk_label_new (_("Le Nombre d'etudiants \nde ce niveau est :"));
  gtk_widget_show (label327);
  gtk_fixed_put (GTK_FIXED (fixed4), label327, 40, 224);
  gtk_widget_set_size_request (label327, 176, 48);

  label325 = gtk_label_new (_("merci de saisir le niveau\n (1,2,3,4 ou 5)"));
  gtk_widget_show (label325);
  gtk_fixed_put (GTK_FIXED (fixed4), label325, 32, 128);
  gtk_widget_set_size_request (label325, 184, 40);

  button_calculEtudiant = gtk_button_new ();
  gtk_widget_show (button_calculEtudiant);
  gtk_fixed_put (GTK_FIXED (fixed4), button_calculEtudiant, 200, 184);
  gtk_widget_set_size_request (button_calculEtudiant, 90, 29);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button_calculEtudiant), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image113 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image113);
  gtk_box_pack_start (GTK_BOX (hbox26), image113, FALSE, FALSE, 0);

  label326 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label326);
  gtk_box_pack_start (GTK_BOX (hbox26), label326, FALSE, FALSE, 0);

  buttonEspaceAjouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonEspaceAjouter);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonEspaceAjouter, 296, 24);
  gtk_widget_set_size_request (buttonEspaceAjouter, 80, 32);

  buttonActualiser = gtk_button_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (buttonActualiser);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonActualiser, 376, 24);
  gtk_widget_set_size_request (buttonActualiser, 80, 32);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_calculEtudiant, "clicked",
                    G_CALLBACK (on_button_calculEtudiant_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonEspaceAjouter, "clicked",
                    G_CALLBACK (on_buttonEspaceAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonActualiser, "clicked",
                    G_CALLBACK (on_buttonActualiseryo_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (etudiant, etudiant, "etudiant");
  GLADE_HOOKUP_OBJECT (etudiant, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (etudiant, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (etudiant, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (etudiant, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (etudiant, label327, "label327");
  GLADE_HOOKUP_OBJECT (etudiant, label325, "label325");
  GLADE_HOOKUP_OBJECT (etudiant, button_calculEtudiant, "button_calculEtudiant");
  GLADE_HOOKUP_OBJECT (etudiant, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (etudiant, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (etudiant, image113, "image113");
  GLADE_HOOKUP_OBJECT (etudiant, label326, "label326");
  GLADE_HOOKUP_OBJECT (etudiant, buttonEspaceAjouter, "buttonEspaceAjouter");
  GLADE_HOOKUP_OBJECT (etudiant, buttonActualiser, "buttonActualiser");

  return etudiant;
}

GtkWidget*
create_ajouterEtudiant (void)
{
  GtkWidget *ajouterEtudiant;
  GtkWidget *fixed5;
  GtkWidget *entry8;
  GtkWidget *entry10;
  GtkWidget *entry12;
  GtkWidget *label329;
  GtkWidget *checkbuttonFoyer;
  GtkWidget *checkbuttonRestau;
  GtkWidget *label328;
  GtkWidget *label330;
  GtkWidget *label333;
  GtkWidget *radiobuttonMale;
  GSList *radiobuttonMale_group = NULL;
  GtkWidget *radiobuttonFemelle;
  GtkWidget *label331;
  GtkWidget *buttonAjouterEtudiant;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image114;
  GtkWidget *label334;

  ajouterEtudiant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouterEtudiant), _("Ajouter Etudiant"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (ajouterEtudiant), fixed5);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed5), entry8, 216, 32);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed5), entry10, 216, 128);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed5), entry12, 216, 80);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label329 = gtk_label_new (_("Niveau"));
  gtk_widget_show (label329);
  gtk_fixed_put (GTK_FIXED (fixed5), label329, 96, 80);
  gtk_widget_set_size_request (label329, 57, 17);

  checkbuttonFoyer = gtk_check_button_new_with_mnemonic (_("foyer"));
  gtk_widget_show (checkbuttonFoyer);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonFoyer, 216, 232);
  gtk_widget_set_size_request (checkbuttonFoyer, 72, 24);

  checkbuttonRestau = gtk_check_button_new_with_mnemonic (_("restau"));
  gtk_widget_show (checkbuttonRestau);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbuttonRestau, 296, 232);
  gtk_widget_set_size_request (checkbuttonRestau, 118, 24);

  label328 = gtk_label_new (_("ID :"));
  gtk_widget_show (label328);
  gtk_fixed_put (GTK_FIXED (fixed5), label328, 80, 32);
  gtk_widget_set_size_request (label328, 57, 17);

  label330 = gtk_label_new (_("Vaccin covid"));
  gtk_widget_show (label330);
  gtk_fixed_put (GTK_FIXED (fixed5), label330, 88, 128);
  gtk_widget_set_size_request (label330, 104, 24);

  label333 = gtk_label_new (_("Abonement :"));
  gtk_widget_show (label333);
  gtk_fixed_put (GTK_FIXED (fixed5), label333, 88, 232);
  gtk_widget_set_size_request (label333, 97, 25);

  radiobuttonMale = gtk_radio_button_new_with_mnemonic (NULL, _("male \n"));
  gtk_widget_show (radiobuttonMale);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobuttonMale, 216, 176);
  gtk_widget_set_size_request (radiobuttonMale, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonMale), radiobuttonMale_group);
  radiobuttonMale_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonMale));

  radiobuttonFemelle = gtk_radio_button_new_with_mnemonic (NULL, _("femelle"));
  gtk_widget_show (radiobuttonFemelle);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobuttonFemelle, 296, 176);
  gtk_widget_set_size_request (radiobuttonFemelle, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonFemelle), radiobuttonMale_group);
  radiobuttonMale_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonFemelle));

  label331 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label331);
  gtk_fixed_put (GTK_FIXED (fixed5), label331, 88, 184);
  gtk_widget_set_size_request (label331, 57, 17);

  buttonAjouterEtudiant = gtk_button_new ();
  gtk_widget_show (buttonAjouterEtudiant);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonAjouterEtudiant, 200, 280);
  gtk_widget_set_size_request (buttonAjouterEtudiant, 96, 32);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (buttonAjouterEtudiant), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image114 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image114);
  gtk_box_pack_start (GTK_BOX (hbox27), image114, FALSE, FALSE, 0);

  label334 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label334);
  gtk_box_pack_start (GTK_BOX (hbox27), label334, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) checkbuttonFoyer, "toggled",
                    G_CALLBACK (on_checkbuttonFoyer_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonRestau, "toggled",
                    G_CALLBACK (on_checkbuttonRestau_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonMale, "toggled",
                    G_CALLBACK (on_radiobuttonMale_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonFemelle, "toggled",
                    G_CALLBACK (on_radiobuttonFemelle_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouterEtudiant, "clicked",
                    G_CALLBACK (on_buttonAjouterEtudiant_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouterEtudiant, ajouterEtudiant, "ajouterEtudiant");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, label329, "label329");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, checkbuttonFoyer, "checkbuttonFoyer");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, checkbuttonRestau, "checkbuttonRestau");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, label328, "label328");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, label330, "label330");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, label333, "label333");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, radiobuttonMale, "radiobuttonMale");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, radiobuttonFemelle, "radiobuttonFemelle");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, label331, "label331");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, buttonAjouterEtudiant, "buttonAjouterEtudiant");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, image114, "image114");
  GLADE_HOOKUP_OBJECT (ajouterEtudiant, label334, "label334");

  return ajouterEtudiant;
}

GtkWidget*
create_recherchee (void)
{
  GtkWidget *recherchee;
  GtkWidget *fixed6;
  GtkWidget *entry13;
  GtkWidget *label341;
  GtkWidget *label340;
  GtkWidget *label342;
  GtkWidget *label339;
  GtkWidget *label338;
  GtkWidget *label336;
  GtkWidget *button8_chercher;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image116;
  GtkWidget *label337;
  GtkWidget *label347_prenom;
  GtkWidget *label344_nom;
  GtkWidget *label345_username;
  GtkWidget *label346_role;
  GtkWidget *label343_tel;

  recherchee = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (recherchee), _("window7"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (recherchee), fixed6);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed6), entry13, 280, 40);
  gtk_widget_set_size_request (entry13, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  label341 = gtk_label_new (_("Num telephone :"));
  gtk_widget_show (label341);
  gtk_fixed_put (GTK_FIXED (fixed6), label341, 16, 288);
  gtk_widget_set_size_request (label341, 128, 24);

  label340 = gtk_label_new (_("Role:"));
  gtk_widget_show (label340);
  gtk_fixed_put (GTK_FIXED (fixed6), label340, 64, 248);
  gtk_widget_set_size_request (label340, 57, 17);

  label342 = gtk_label_new (_("Username :"));
  gtk_widget_show (label342);
  gtk_fixed_put (GTK_FIXED (fixed6), label342, 24, 208);
  gtk_widget_set_size_request (label342, 96, 16);

  label339 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label339);
  gtk_fixed_put (GTK_FIXED (fixed6), label339, 56, 168);
  gtk_widget_set_size_request (label339, 57, 17);

  label338 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label338);
  gtk_fixed_put (GTK_FIXED (fixed6), label338, 48, 128);
  gtk_widget_set_size_request (label338, 57, 17);

  label336 = gtk_label_new (_("ID:"));
  gtk_widget_show (label336);
  gtk_fixed_put (GTK_FIXED (fixed6), label336, 208, 48);
  gtk_widget_set_size_request (label336, 64, 16);

  button8_chercher = gtk_button_new ();
  gtk_widget_show (button8_chercher);
  gtk_fixed_put (GTK_FIXED (fixed6), button8_chercher, 456, 40);
  gtk_widget_set_size_request (button8_chercher, 96, 32);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button8_chercher), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image116 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image116);
  gtk_box_pack_start (GTK_BOX (hbox29), image116, FALSE, FALSE, 0);

  label337 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label337);
  gtk_box_pack_start (GTK_BOX (hbox29), label337, FALSE, FALSE, 0);

  label347_prenom = gtk_label_new ("");
  gtk_widget_show (label347_prenom);
  gtk_fixed_put (GTK_FIXED (fixed6), label347_prenom, 128, 128);
  gtk_widget_set_size_request (label347_prenom, 57, 17);

  label344_nom = gtk_label_new ("");
  gtk_widget_show (label344_nom);
  gtk_fixed_put (GTK_FIXED (fixed6), label344_nom, 136, 168);
  gtk_widget_set_size_request (label344_nom, 57, 17);

  label345_username = gtk_label_new ("");
  gtk_widget_show (label345_username);
  gtk_fixed_put (GTK_FIXED (fixed6), label345_username, 136, 208);
  gtk_widget_set_size_request (label345_username, 57, 17);

  label346_role = gtk_label_new ("");
  gtk_widget_show (label346_role);
  gtk_fixed_put (GTK_FIXED (fixed6), label346_role, 136, 248);
  gtk_widget_set_size_request (label346_role, 57, 17);

  label343_tel = gtk_label_new ("");
  gtk_widget_show (label343_tel);
  gtk_fixed_put (GTK_FIXED (fixed6), label343_tel, 152, 288);
  gtk_widget_set_size_request (label343_tel, 57, 17);

  g_signal_connect ((gpointer) button8_chercher, "clicked",
                    G_CALLBACK (on_button8_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherchee, recherchee, "recherchee");
  GLADE_HOOKUP_OBJECT (recherchee, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (recherchee, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (recherchee, label341, "label341");
  GLADE_HOOKUP_OBJECT (recherchee, label340, "label340");
  GLADE_HOOKUP_OBJECT (recherchee, label342, "label342");
  GLADE_HOOKUP_OBJECT (recherchee, label339, "label339");
  GLADE_HOOKUP_OBJECT (recherchee, label338, "label338");
  GLADE_HOOKUP_OBJECT (recherchee, label336, "label336");
  GLADE_HOOKUP_OBJECT (recherchee, button8_chercher, "button8_chercher");
  GLADE_HOOKUP_OBJECT (recherchee, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (recherchee, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (recherchee, image116, "image116");
  GLADE_HOOKUP_OBJECT (recherchee, label337, "label337");
  GLADE_HOOKUP_OBJECT (recherchee, label347_prenom, "label347_prenom");
  GLADE_HOOKUP_OBJECT (recherchee, label344_nom, "label344_nom");
  GLADE_HOOKUP_OBJECT (recherchee, label345_username, "label345_username");
  GLADE_HOOKUP_OBJECT (recherchee, label346_role, "label346_role");
  GLADE_HOOKUP_OBJECT (recherchee, label343_tel, "label343_tel");

  return recherchee;
}

