/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_nutritionniste (void)
{
  GtkWidget *nutritionniste;
  GtkWidget *fixed1;
  GtkWidget *button7_quitter;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image18;
  GtkWidget *label85;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *treeview3;
  GtkWidget *entry1_plat;
  GtkWidget *entry2_entree;
  GtkWidget *entry3_platprincipal;
  GtkWidget *entry4_dessert;
  GtkWidget *entry5_boisson;
  GtkWidget *button3_supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label29;
  GtkWidget *checkbutton1_supprimer;
  GtkWidget *label89_supprimer;
  GtkWidget *button5_actualiser;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image20;
  GtkWidget *label87;
  GtkWidget *label88_modification;
  GtkWidget *label20_modifier;
  GtkWidget *label22_plat;
  GtkWidget *button4_recherche;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image19;
  GtkWidget *label86;
  GtkWidget *label24_platprincipal;
  GtkWidget *label26_boisson;
  GtkWidget *label25_dessert;
  GtkWidget *label23_entree;
  GtkWidget *checkbutton2_modifier;
  GtkWidget *button2_modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label28;
  GtkWidget *label2_modifier_supprimer;
  GtkWidget *fixed2;
  GtkWidget *entry1_menu;
  GtkWidget *entry11;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *entry14_platprincipal;
  GtkWidget *entry15_boisson;
  GtkWidget *entry16_dessert;
  GtkWidget *entry17_entree;
  GtkWidget *button1_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;
  GtkWidget *checkbutton1_ajouter;
  GtkWidget *controle_glucide;
  GtkWidget *controle_proteine;
  GtkWidget *controle_lipide;
  GtkWidget *label86_message;
  GtkWidget *label90;
  GtkWidget *controle_calorie;
  GtkWidget *radiobutton3_dinner;
  GSList *radiobutton3_dinner_group = NULL;
  GtkWidget *radiobutton2_dejeuner;
  GtkWidget *radiobutton1_petit_dejuner;
  GtkWidget *label4_repas;
  GtkWidget *label88;
  GtkWidget *combobox1;
  GtkWidget *label40_;
  GtkWidget *label6_nb_entree;
  GtkWidget *label5_plat;
  GtkWidget *label7_platprincipal;
  GtkWidget *label8_dessert;
  GtkWidget *label9_boisson;
  GtkWidget *label34_jour;
  GtkWidget *label10_date;
  GtkWidget *label35_mois;
  GtkWidget *label36_annee;
  GtkWidget *label1_ajouter;
  GtkWidget *fixed4;
  GtkWidget *treeview2;
  GtkWidget *entry12;
  GtkWidget *button4_chercher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label31;
  GtkWidget *label33_id;
  GtkWidget *button2;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image10;
  GtkWidget *label38;
  GtkWidget *label88_meilleur;
  GtkWidget *label3_chercher;

  nutritionniste = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (nutritionniste, 1800, 800);
  gtk_window_set_title (GTK_WINDOW (nutritionniste), _("Nutritionniste"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (nutritionniste), fixed1);

  button7_quitter = gtk_button_new ();
  gtk_widget_show (button7_quitter);
  gtk_fixed_put (GTK_FIXED (fixed1), button7_quitter, 960, 48);
  gtk_widget_set_size_request (button7_quitter, 128, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button7_quitter), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image18 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox11), image18, FALSE, FALSE, 0);

  label85 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (hbox11), label85, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 536, 112);
  gtk_widget_set_size_request (notebook1, 1248, 680);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview3, 16, 128);
  gtk_widget_set_size_request (treeview3, 832, 400);

  entry1_plat = gtk_entry_new ();
  gtk_widget_show (entry1_plat);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1_plat, 952, 120);
  gtk_widget_set_size_request (entry1_plat, 224, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_plat), 8226);

  entry2_entree = gtk_entry_new ();
  gtk_widget_show (entry2_entree);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2_entree, 1024, 304);
  gtk_widget_set_size_request (entry2_entree, 72, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_entree), 8226);

  entry3_platprincipal = gtk_entry_new ();
  gtk_widget_show (entry3_platprincipal);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3_platprincipal, 1024, 176);
  gtk_widget_set_size_request (entry3_platprincipal, 72, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_platprincipal), 8226);

  entry4_dessert = gtk_entry_new ();
  gtk_widget_show (entry4_dessert);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4_dessert, 1024, 256);
  gtk_widget_set_size_request (entry4_dessert, 72, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_dessert), 8226);

  entry5_boisson = gtk_entry_new ();
  gtk_widget_show (entry5_boisson);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5_boisson, 1024, 216);
  gtk_widget_set_size_request (entry5_boisson, 72, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_boisson), 8226);

  button3_supprimer = gtk_button_new ();
  gtk_widget_show (button3_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), button3_supprimer, 120, 600);
  gtk_widget_set_size_request (button3_supprimer, 184, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button3_supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("<b><span \ncolor=\"black\">Supprimer</span></b>"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox4), label29, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  checkbutton1_supprimer = gtk_check_button_new_with_mnemonic (_("\303\252tes-vous sur de vouloir supprimer le menu s\303\251lectionn\303\251"));
  gtk_widget_show (checkbutton1_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1_supprimer, 0, 496);
  gtk_widget_set_size_request (checkbutton1_supprimer, 504, 96);

  label89_supprimer = gtk_label_new ("");
  gtk_widget_show (label89_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), label89_supprimer, 392, 600);
  gtk_widget_set_size_request (label89_supprimer, 152, 41);

  button5_actualiser = gtk_button_new ();
  gtk_widget_show (button5_actualiser);
  gtk_fixed_put (GTK_FIXED (fixed3), button5_actualiser, 440, 48);
  gtk_widget_set_size_request (button5_actualiser, 136, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button5_actualiser), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image20 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox13), image20, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("<b><span \ncolor=\"black\">Actualiser</span></b>"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox13), label87, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label87), TRUE);

  label88_modification = gtk_label_new ("");
  gtk_widget_show (label88_modification);
  gtk_fixed_put (GTK_FIXED (fixed3), label88_modification, 1424, 480);
  gtk_widget_set_size_request (label88_modification, 248, 41);

  label20_modifier = gtk_label_new_with_mnemonic (_("<b><span font=\"18px\"\ncolor=\"red\">Modifier ces donn\303\251es:</span></b>"));
  gtk_widget_show (label20_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), label20_modifier, 920, 56);
  gtk_widget_set_size_request (label20_modifier, 208, 55);
  gtk_label_set_use_markup (GTK_LABEL (label20_modifier), TRUE);

  label22_plat = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">plat:</span></b>"));
  gtk_widget_show (label22_plat);
  gtk_fixed_put (GTK_FIXED (fixed3), label22_plat, 848, 120);
  gtk_widget_set_size_request (label22_plat, 145, 41);
  gtk_label_set_use_markup (GTK_LABEL (label22_plat), TRUE);

  button4_recherche = gtk_button_new ();
  gtk_widget_show (button4_recherche);
  gtk_fixed_put (GTK_FIXED (fixed3), button4_recherche, 576, 528);
  gtk_widget_set_size_request (button4_recherche, 144, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button4_recherche), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox12), image19, FALSE, FALSE, 0);

  label86 = gtk_label_new_with_mnemonic (_("<b><span \ncolor=\"black\">Afficher</span></b>"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox12), label86, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label86), TRUE);

  label24_platprincipal = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">PLAT PRINCIPALE:</span></b>"));
  gtk_widget_show (label24_platprincipal);
  gtk_fixed_put (GTK_FIXED (fixed3), label24_platprincipal, 864, 176);
  gtk_widget_set_size_request (label24_platprincipal, 160, 41);
  gtk_label_set_use_markup (GTK_LABEL (label24_platprincipal), TRUE);

  label26_boisson = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">BOISSION:</span></b>"));
  gtk_widget_show (label26_boisson);
  gtk_fixed_put (GTK_FIXED (fixed3), label26_boisson, 864, 216);
  gtk_widget_set_size_request (label26_boisson, 168, 41);
  gtk_label_set_use_markup (GTK_LABEL (label26_boisson), TRUE);

  label25_dessert = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">DESSERT:</span></b>"));
  gtk_widget_show (label25_dessert);
  gtk_fixed_put (GTK_FIXED (fixed3), label25_dessert, 880, 256);
  gtk_widget_set_size_request (label25_dessert, 145, 41);
  gtk_label_set_use_markup (GTK_LABEL (label25_dessert), TRUE);

  label23_entree = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">ENTREE:</span></b>"));
  gtk_widget_show (label23_entree);
  gtk_fixed_put (GTK_FIXED (fixed3), label23_entree, 880, 296);
  gtk_widget_set_size_request (label23_entree, 145, 41);
  gtk_label_set_use_markup (GTK_LABEL (label23_entree), TRUE);

  checkbutton2_modifier = gtk_check_button_new_with_mnemonic (_("\303\252tes-vous sur de vouloir effectuer des modifications"));
  gtk_widget_show (checkbutton2_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2_modifier, 864, 344);
  gtk_widget_set_size_request (checkbutton2_modifier, 416, 48);

  button2_modifier = gtk_button_new ();
  gtk_widget_show (button2_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button2_modifier, 1040, 400);
  gtk_widget_set_size_request (button2_modifier, 200, 45);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button2_modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("<b><span \ncolor=\"black\">Modifier</span></b>"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox3), label28, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label2_modifier_supprimer = gtk_label_new_with_mnemonic (_("   <b><span\ncolor=\"red\">    Afficher   </span></b>"));
  gtk_widget_show (label2_modifier_supprimer);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2_modifier_supprimer);
  gtk_label_set_use_markup (GTK_LABEL (label2_modifier_supprimer), TRUE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entry1_menu = gtk_entry_new ();
  gtk_widget_show (entry1_menu);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_menu, 464, 240);
  gtk_widget_set_size_request (entry1_menu, 184, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_menu), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed2), entry11, 480, 96);
  gtk_widget_set_size_request (entry11, 184, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 448, 504);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 568, 504);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1, 2000, 2021, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 696, 504);
  gtk_widget_set_size_request (annee, 60, 27);

  entry14_platprincipal = gtk_entry_new ();
  gtk_widget_show (entry14_platprincipal);
  gtk_fixed_put (GTK_FIXED (fixed2), entry14_platprincipal, 464, 336);
  gtk_widget_set_size_request (entry14_platprincipal, 184, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14_platprincipal), 8226);

  entry15_boisson = gtk_entry_new ();
  gtk_widget_show (entry15_boisson);
  gtk_fixed_put (GTK_FIXED (fixed2), entry15_boisson, 464, 432);
  gtk_widget_set_size_request (entry15_boisson, 184, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15_boisson), 8226);

  entry16_dessert = gtk_entry_new ();
  gtk_widget_show (entry16_dessert);
  gtk_fixed_put (GTK_FIXED (fixed2), entry16_dessert, 464, 384);
  gtk_widget_set_size_request (entry16_dessert, 184, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16_dessert), 8226);

  entry17_entree = gtk_entry_new ();
  gtk_widget_show (entry17_entree);
  gtk_fixed_put (GTK_FIXED (fixed2), entry17_entree, 464, 288);
  gtk_widget_set_size_request (entry17_entree, 184, 39);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17_entree), 8226);

  button1_ajouter = gtk_button_new ();
  gtk_widget_show (button1_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button1_ajouter, 376, 600);
  gtk_widget_set_size_request (button1_ajouter, 208, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("<b><span \ncolor=\"black\">Ajouter</span></b>"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  checkbutton1_ajouter = gtk_check_button_new_with_mnemonic (_("\303\252tes-vous s\303\273r de vouloir ajouter ce menu "));
  gtk_widget_show (checkbutton1_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1_ajouter, 328, 544);
  gtk_widget_set_size_request (checkbutton1_ajouter, 312, 40);

  controle_glucide = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (controle_glucide);
  gtk_fixed_put (GTK_FIXED (fixed2), controle_glucide, 1040, 384);
  gtk_widget_set_size_request (controle_glucide, 248, 41);
  gtk_label_set_use_markup (GTK_LABEL (controle_glucide), TRUE);

  controle_proteine = gtk_label_new ("");
  gtk_widget_show (controle_proteine);
  gtk_fixed_put (GTK_FIXED (fixed2), controle_proteine, 1064, 312);
  gtk_widget_set_size_request (controle_proteine, 168, 32);

  controle_lipide = gtk_label_new ("");
  gtk_widget_show (controle_lipide);
  gtk_fixed_put (GTK_FIXED (fixed2), controle_lipide, 464, 384);
  gtk_widget_set_size_request (controle_lipide, 192, 40);

  label86_message = gtk_label_new ("");
  gtk_widget_show (label86_message);
  gtk_fixed_put (GTK_FIXED (fixed2), label86_message, 592, 608);
  gtk_widget_set_size_request (label86_message, 160, 40);

  label90 = gtk_label_new ("");
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed2), label90, 568, 96);
  gtk_widget_set_size_request (label90, 192, 33);

  controle_calorie = gtk_label_new ("");
  gtk_widget_show (controle_calorie);
  gtk_fixed_put (GTK_FIXED (fixed2), controle_calorie, 456, 304);
  gtk_widget_set_size_request (controle_calorie, 152, 41);

  radiobutton3_dinner = gtk_radio_button_new_with_mnemonic (NULL, _("dinner"));
  gtk_widget_show (radiobutton3_dinner);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3_dinner, 776, 160);
  gtk_widget_set_size_request (radiobutton3_dinner, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3_dinner), radiobutton3_dinner_group);
  radiobutton3_dinner_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3_dinner));

  radiobutton2_dejeuner = gtk_radio_button_new_with_mnemonic (NULL, _("dejeuner"));
  gtk_widget_show (radiobutton2_dejeuner);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2_dejeuner, 624, 160);
  gtk_widget_set_size_request (radiobutton2_dejeuner, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_dejeuner), radiobutton3_dinner_group);
  radiobutton3_dinner_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_dejeuner));

  radiobutton1_petit_dejuner = gtk_radio_button_new_with_mnemonic (NULL, _("PetitDejeuner"));
  gtk_widget_show (radiobutton1_petit_dejuner);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1_petit_dejuner, 456, 160);
  gtk_widget_set_size_request (radiobutton1_petit_dejuner, 136, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_petit_dejuner), radiobutton3_dinner_group);
  radiobutton3_dinner_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_petit_dejuner));

  label4_repas = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">le repas:</span></b>"));
  gtk_widget_show (label4_repas);
  gtk_fixed_put (GTK_FIXED (fixed2), label4_repas, 264, 152);
  gtk_widget_set_size_request (label4_repas, 184, 40);
  gtk_label_set_use_markup (GTK_LABEL (label4_repas), TRUE);

  label88 = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">ID:</span></b>"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed2), label88, 328, 104);
  gtk_widget_set_size_request (label88, 136, 33);
  gtk_label_set_use_markup (GTK_LABEL (label88), TRUE);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 464, 200);
  gtk_widget_set_size_request (combobox1, 184, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("5"));

  label40_ = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">menu:</span></b>"));
  gtk_widget_show (label40_);
  gtk_fixed_put (GTK_FIXED (fixed2), label40_, 344, 208);
  gtk_widget_set_size_request (label40_, 112, 25);
  gtk_label_set_use_markup (GTK_LABEL (label40_), TRUE);

  label6_nb_entree = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">ENTREE:</span></b>"));
  gtk_widget_show (label6_nb_entree);
  gtk_fixed_put (GTK_FIXED (fixed2), label6_nb_entree, 296, 296);
  gtk_widget_set_size_request (label6_nb_entree, 184, 33);
  gtk_label_set_use_markup (GTK_LABEL (label6_nb_entree), TRUE);

  label5_plat = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">plat:</span></b>"));
  gtk_widget_show (label5_plat);
  gtk_fixed_put (GTK_FIXED (fixed2), label5_plat, 328, 240);
  gtk_widget_set_size_request (label5_plat, 144, 41);
  gtk_label_set_use_markup (GTK_LABEL (label5_plat), TRUE);

  label7_platprincipal = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">PLAT PRINCIPALE:</span></b>"));
  gtk_widget_show (label7_platprincipal);
  gtk_fixed_put (GTK_FIXED (fixed2), label7_platprincipal, 288, 328);
  gtk_widget_set_size_request (label7_platprincipal, 184, 49);
  gtk_label_set_use_markup (GTK_LABEL (label7_platprincipal), TRUE);

  label8_dessert = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">DESSERT:</span></b>"));
  gtk_widget_show (label8_dessert);
  gtk_fixed_put (GTK_FIXED (fixed2), label8_dessert, 288, 392);
  gtk_widget_set_size_request (label8_dessert, 184, 33);
  gtk_label_set_use_markup (GTK_LABEL (label8_dessert), TRUE);

  label9_boisson = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">BOISSON:</span></b>"));
  gtk_widget_show (label9_boisson);
  gtk_fixed_put (GTK_FIXED (fixed2), label9_boisson, 304, 440);
  gtk_widget_set_size_request (label9_boisson, 184, 33);
  gtk_label_set_use_markup (GTK_LABEL (label9_boisson), TRUE);

  label34_jour = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">jour:</span></b>"));
  gtk_widget_show (label34_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), label34_jour, 376, 504);
  gtk_widget_set_size_request (label34_jour, 56, 25);
  gtk_label_set_use_markup (GTK_LABEL (label34_jour), TRUE);

  label10_date = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">Date:</span></b>"));
  gtk_widget_show (label10_date);
  gtk_fixed_put (GTK_FIXED (fixed2), label10_date, 288, 496);
  gtk_widget_set_size_request (label10_date, 105, 41);
  gtk_label_set_use_markup (GTK_LABEL (label10_date), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label10_date), 0.5, 0.53);

  label35_mois = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">mois:</span></b>"));
  gtk_widget_show (label35_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), label35_mois, 504, 504);
  gtk_widget_set_size_request (label35_mois, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label35_mois), TRUE);

  label36_annee = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"black\">ann\303\251e:</span></b>"));
  gtk_widget_show (label36_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), label36_annee, 632, 504);
  gtk_widget_set_size_request (label36_annee, 65, 25);
  gtk_label_set_use_markup (GTK_LABEL (label36_annee), TRUE);

  label1_ajouter = gtk_label_new_with_mnemonic (_("<b><span\ncolor=\"red\">    Ajouter    </span></b>"));
  gtk_widget_show (label1_ajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label1_ajouter);
  gtk_label_set_use_markup (GTK_LABEL (label1_ajouter), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 120, 192);
  gtk_widget_set_size_request (treeview2, 784, 296);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed4), entry12, 248, 80);
  gtk_widget_set_size_request (entry12, 176, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  button4_chercher = gtk_button_new ();
  gtk_widget_show (button4_chercher);
  gtk_fixed_put (GTK_FIXED (fixed4), button4_chercher, 456, 80);
  gtk_widget_set_size_request (button4_chercher, 176, 45);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4_chercher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("<b><span \ncolor=\"black\">chercher</span></b>"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox5), label31, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label33_id = gtk_label_new_with_mnemonic (_("<b><span font=\"18px\"\ncolor=\"red\">donner le nom de plat</span></b>"));
  gtk_widget_show (label33_id);
  gtk_fixed_put (GTK_FIXED (fixed4), label33_id, 24, 80);
  gtk_widget_set_size_request (label33_id, 216, 40);
  gtk_label_set_use_markup (GTK_LABEL (label33_id), TRUE);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 968, 456);
  gtk_widget_set_size_request (button2, 216, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button2), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox6), image10, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("<b><span \ncolor=\"black\">Meilleur menu</span></b>"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox6), label38, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label88_meilleur = gtk_label_new ("");
  gtk_widget_show (label88_meilleur);
  gtk_fixed_put (GTK_FIXED (fixed4), label88_meilleur, 976, 408);
  gtk_widget_set_size_request (label88_meilleur, 200, 41);

  label3_chercher = gtk_label_new_with_mnemonic (_(" <b><span\ncolor=\"red\">    Chercher    </span></b>"));
  gtk_widget_show (label3_chercher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3_chercher);
  gtk_label_set_use_markup (GTK_LABEL (label3_chercher), TRUE);

  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button3_supprimer, "clicked",
                    G_CALLBACK (on_button3_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_supprimer, "toggled",
                    G_CALLBACK (on_checkbutton1_supprimer_toggled),
                    NULL);
  g_signal_connect ((gpointer) button5_actualiser, "clicked",
                    G_CALLBACK (on_button5_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_recherche, "clicked",
                    G_CALLBACK (on_button4_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2_modifier, "toggled",
                    G_CALLBACK (on_checkbutton2_modifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) button2_modifier, "clicked",
                    G_CALLBACK (on_button2_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_ajouter, "clicked",
                    G_CALLBACK (on_button1_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_ajouter, "toggled",
                    G_CALLBACK (on_checkbutton1_ajouter_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3_dinner, "toggled",
                    G_CALLBACK (on_radiobutton3_dinner_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_dejeuner, "toggled",
                    G_CALLBACK (on_radiobutton2_dejeuner_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_petit_dejuner, "toggled",
                    G_CALLBACK (on_radiobutton1_petit_dejuner_toggled),
                    NULL);
  g_signal_connect ((gpointer) button4_chercher, "clicked",
                    G_CALLBACK (on_button4_chercher_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label22_plat), entry1_plat);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label24_platprincipal), entry3_platprincipal);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label26_boisson), entry5_boisson);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label25_dessert), entry4_dessert);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label23_entree), entry2_entree);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label4_repas), radiobutton1_petit_dejuner);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label88), radiobutton1_petit_dejuner);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label5_plat), entry1_menu);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label7_platprincipal), entry14_platprincipal);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label9_boisson), entry15_boisson);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label34_jour), jour);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label35_mois), mois);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label36_annee), annee);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label33_id), entry12);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nutritionniste, nutritionniste, "nutritionniste");
  GLADE_HOOKUP_OBJECT (nutritionniste, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (nutritionniste, button7_quitter, "button7_quitter");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (nutritionniste, image18, "image18");
  GLADE_HOOKUP_OBJECT (nutritionniste, label85, "label85");
  GLADE_HOOKUP_OBJECT (nutritionniste, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (nutritionniste, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (nutritionniste, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry1_plat, "entry1_plat");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry2_entree, "entry2_entree");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry3_platprincipal, "entry3_platprincipal");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry4_dessert, "entry4_dessert");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry5_boisson, "entry5_boisson");
  GLADE_HOOKUP_OBJECT (nutritionniste, button3_supprimer, "button3_supprimer");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (nutritionniste, image5, "image5");
  GLADE_HOOKUP_OBJECT (nutritionniste, label29, "label29");
  GLADE_HOOKUP_OBJECT (nutritionniste, checkbutton1_supprimer, "checkbutton1_supprimer");
  GLADE_HOOKUP_OBJECT (nutritionniste, label89_supprimer, "label89_supprimer");
  GLADE_HOOKUP_OBJECT (nutritionniste, button5_actualiser, "button5_actualiser");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (nutritionniste, image20, "image20");
  GLADE_HOOKUP_OBJECT (nutritionniste, label87, "label87");
  GLADE_HOOKUP_OBJECT (nutritionniste, label88_modification, "label88_modification");
  GLADE_HOOKUP_OBJECT (nutritionniste, label20_modifier, "label20_modifier");
  GLADE_HOOKUP_OBJECT (nutritionniste, label22_plat, "label22_plat");
  GLADE_HOOKUP_OBJECT (nutritionniste, button4_recherche, "button4_recherche");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (nutritionniste, image19, "image19");
  GLADE_HOOKUP_OBJECT (nutritionniste, label86, "label86");
  GLADE_HOOKUP_OBJECT (nutritionniste, label24_platprincipal, "label24_platprincipal");
  GLADE_HOOKUP_OBJECT (nutritionniste, label26_boisson, "label26_boisson");
  GLADE_HOOKUP_OBJECT (nutritionniste, label25_dessert, "label25_dessert");
  GLADE_HOOKUP_OBJECT (nutritionniste, label23_entree, "label23_entree");
  GLADE_HOOKUP_OBJECT (nutritionniste, checkbutton2_modifier, "checkbutton2_modifier");
  GLADE_HOOKUP_OBJECT (nutritionniste, button2_modifier, "button2_modifier");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (nutritionniste, image4, "image4");
  GLADE_HOOKUP_OBJECT (nutritionniste, label28, "label28");
  GLADE_HOOKUP_OBJECT (nutritionniste, label2_modifier_supprimer, "label2_modifier_supprimer");
  GLADE_HOOKUP_OBJECT (nutritionniste, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry1_menu, "entry1_menu");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (nutritionniste, jour, "jour");
  GLADE_HOOKUP_OBJECT (nutritionniste, mois, "mois");
  GLADE_HOOKUP_OBJECT (nutritionniste, annee, "annee");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry14_platprincipal, "entry14_platprincipal");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry15_boisson, "entry15_boisson");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry16_dessert, "entry16_dessert");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry17_entree, "entry17_entree");
  GLADE_HOOKUP_OBJECT (nutritionniste, button1_ajouter, "button1_ajouter");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (nutritionniste, image1, "image1");
  GLADE_HOOKUP_OBJECT (nutritionniste, label11, "label11");
  GLADE_HOOKUP_OBJECT (nutritionniste, checkbutton1_ajouter, "checkbutton1_ajouter");
  GLADE_HOOKUP_OBJECT (nutritionniste, controle_glucide, "controle_glucide");
  GLADE_HOOKUP_OBJECT (nutritionniste, controle_proteine, "controle_proteine");
  GLADE_HOOKUP_OBJECT (nutritionniste, controle_lipide, "controle_lipide");
  GLADE_HOOKUP_OBJECT (nutritionniste, label86_message, "label86_message");
  GLADE_HOOKUP_OBJECT (nutritionniste, label90, "label90");
  GLADE_HOOKUP_OBJECT (nutritionniste, controle_calorie, "controle_calorie");
  GLADE_HOOKUP_OBJECT (nutritionniste, radiobutton3_dinner, "radiobutton3_dinner");
  GLADE_HOOKUP_OBJECT (nutritionniste, radiobutton2_dejeuner, "radiobutton2_dejeuner");
  GLADE_HOOKUP_OBJECT (nutritionniste, radiobutton1_petit_dejuner, "radiobutton1_petit_dejuner");
  GLADE_HOOKUP_OBJECT (nutritionniste, label4_repas, "label4_repas");
  GLADE_HOOKUP_OBJECT (nutritionniste, label88, "label88");
  GLADE_HOOKUP_OBJECT (nutritionniste, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (nutritionniste, label40_, "label40_");
  GLADE_HOOKUP_OBJECT (nutritionniste, label6_nb_entree, "label6_nb_entree");
  GLADE_HOOKUP_OBJECT (nutritionniste, label5_plat, "label5_plat");
  GLADE_HOOKUP_OBJECT (nutritionniste, label7_platprincipal, "label7_platprincipal");
  GLADE_HOOKUP_OBJECT (nutritionniste, label8_dessert, "label8_dessert");
  GLADE_HOOKUP_OBJECT (nutritionniste, label9_boisson, "label9_boisson");
  GLADE_HOOKUP_OBJECT (nutritionniste, label34_jour, "label34_jour");
  GLADE_HOOKUP_OBJECT (nutritionniste, label10_date, "label10_date");
  GLADE_HOOKUP_OBJECT (nutritionniste, label35_mois, "label35_mois");
  GLADE_HOOKUP_OBJECT (nutritionniste, label36_annee, "label36_annee");
  GLADE_HOOKUP_OBJECT (nutritionniste, label1_ajouter, "label1_ajouter");
  GLADE_HOOKUP_OBJECT (nutritionniste, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (nutritionniste, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (nutritionniste, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (nutritionniste, button4_chercher, "button4_chercher");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (nutritionniste, image6, "image6");
  GLADE_HOOKUP_OBJECT (nutritionniste, label31, "label31");
  GLADE_HOOKUP_OBJECT (nutritionniste, label33_id, "label33_id");
  GLADE_HOOKUP_OBJECT (nutritionniste, button2, "button2");
  GLADE_HOOKUP_OBJECT (nutritionniste, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (nutritionniste, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (nutritionniste, image10, "image10");
  GLADE_HOOKUP_OBJECT (nutritionniste, label38, "label38");
  GLADE_HOOKUP_OBJECT (nutritionniste, label88_meilleur, "label88_meilleur");
  GLADE_HOOKUP_OBJECT (nutritionniste, label3_chercher, "label3_chercher");

  return nutritionniste;
}

